# Telecom Customer Churn Intelligence

### Business Analytics and Customer Retention Portfolio Project

**Developed and Designed by Emmanuel Onuoha**

---

## Stage 1 — Project Definition

This stage establishes the business problem, project objectives, scope, stakeholders, and success criteria. It ensures that every later analysis, visualization, model, and recommendation supports a clear business decision.

## 1.1 Executive Summary

A telecommunications company serves customers with different demographic profiles, contracts, services, payment arrangements, and levels of engagement. Some customers remain with the company, some have recently joined, and others discontinue their service. Customer losses reduce recurring revenue, weaken customer lifetime value, and may increase the cost of replacing departing customers.

This project will use customer-level data to measure churn, identify the customer groups most exposed to it, investigate the reasons customers leave, and translate the findings into practical retention actions. The final output will be an interactive decision-support dashboard supported by a transparent and reproducible analytical workflow.

## 1.2 What Customer Churn Means

In this project, **customer churn** means that a customer has ended or discontinued their relationship with the telecom company and is recorded with a churn label of `Yes` and a customer status of `Churned`. Customers labelled `No` have not churned; this group contains customers who stayed as well as customers who recently joined.

The main descriptive churn rate will be calculated as:

**Churn Rate = Number of Churned Customers ÷ Total Number of Customers × 100**

Where a metric requires a different eligible population—for example, separating newly joined customers from established customers—the denominator will be stated clearly.

## 1.3 Business Problem

The company has experienced customer attrition, but an overall churn figure alone does not reveal where the greatest retention risks exist or which interventions should be prioritized. Management needs a reliable way to distinguish high-risk customer segments, understand the commercial and service-related reasons behind churn, and direct retention resources toward actions with the greatest potential value.

Without this insight, retention campaigns may be broad, reactive, expensive, and poorly targeted. The business therefore requires an evidence-based churn intelligence solution that connects customer characteristics and service experiences with churn outcomes, customer value, and appropriate retention responses.

## 1.4 Central Business Question

> **Which customers are most likely to churn, why are they leaving, and what actions could improve retention?**

## 1.5 Project Objectives

1. Measure the size and business significance of customer churn using clearly defined performance indicators.
2. Profile churned, retained, and newly joined customers without treating these groups as interchangeable.
3. Identify demographic, contractual, service, billing, engagement, satisfaction, and geographic patterns associated with churn.
4. Determine the leading recorded churn categories and reasons and assess where the company can realistically intervene.
5. Identify high-risk and high-value customer segments that should receive priority in retention planning.
6. Develop and evaluate an interpretable model that estimates churn risk using information that would reasonably be available before a customer leaves.
7. Translate analytical findings into practical, segment-specific retention recommendations.
8. Present the results in an interactive Streamlit application that supports executive exploration and decision-making.

## 1.6 Business Questions

The project will answer the following questions:

- What is the overall churn rate, and how many customers and how much recurring revenue are associated with churn?
- How does churn vary by tenure, age, senior-citizen status, marital status, and dependents?
- Which contract types, internet services, support services, billing arrangements, and payment methods are associated with higher churn?
- At what point in the customer lifecycle is churn most concentrated?
- Which combinations of customer characteristics define the highest-risk segments?
- What reasons do customers report for leaving, and which reasons appear actionable?
- Are there geographic areas with unusually high churn that require investigation?
- Which high-value customers may warrant proactive retention attention?
- Can churn risk be estimated accurately enough to support targeted outreach?
- Which retention actions should be prioritized for each major risk segment?

## 1.7 Intended Stakeholders

| Stakeholder | Information Required | Decisions Supported |
|---|---|---|
| Executive leadership | Churn exposure, customer value, priority risks, and strategic recommendations | Set retention priorities and allocate resources |
| Customer retention and CRM teams | High-risk segments, customer risk scores, and suggested interventions | Select customers and offers for targeted campaigns |
| Marketing team | Customer profiles, competitor-related losses, referrals, and offer performance | Design segment-specific communication and loyalty offers |
| Customer service leadership | Satisfaction, support interactions, and service-related churn reasons | Improve support quality, training, and escalation procedures |
| Product and network teams | Churn by internet type, service bundle, location, and reliability concerns | Prioritize product, service, and network improvements |
| Finance and commercial teams | Monthly charges, revenue exposure, CLTV, and campaign scenarios | Assess the economic value of retention initiatives |
| Data and analytics teams | Data definitions, model performance, assumptions, and limitations | Reproduce, monitor, and improve the analytical solution |

## 1.8 Decisions the Dashboard Should Support

The final dashboard should enable decision-makers to:

- Locate the customer segments where churn is most concentrated.
- Compare churn performance across contracts, services, customer profiles, and locations.
- Prioritize customers by estimated risk and commercial value.
- Select suitable retention actions for different risk segments.
- Investigate competitor, pricing, service, support, and dissatisfaction-related losses.
- Evaluate simple retention campaign scenarios using customer volume, cost, and expected effectiveness.
- Monitor whether retention initiatives improve business outcomes when refreshed data becomes available.

## 1.9 Project Scope

### In Scope

- Customer-level data-quality assessment and preparation
- Descriptive and diagnostic churn analysis
- Customer segmentation and geographic comparison
- Analysis of recorded churn categories and reasons
- Churn-risk modeling with leakage controls and interpretable outputs
- Business recommendations and retention scenario analysis
- An interactive Streamlit dashboard and supporting project documentation

### Out of Scope

- Claiming that observed relationships prove causation
- Automatically contacting customers or executing retention campaigns
- Production integration with live CRM, billing, or customer-support systems
- Measuring campaign uplift without historical treatment and control-group data
- Generalizing the findings beyond the dataset's represented geography and time period without additional evidence
- Using information recorded only after churn as an input to pre-churn prediction

## 1.10 Success Criteria

The project will be considered successful when it meets the following criteria:

### Analytical Success

- Churn and retention metrics are calculated consistently and can be reconciled to the source data.
- Major churn patterns are quantified with their customer counts, rates, and business context.
- High-risk segments are sufficiently specific to support targeted action.
- Predictive variables are screened for data leakage before modeling.
- Model performance is assessed with suitable classification measures rather than accuracy alone.
- Model limitations, assumptions, and uncertainty are communicated clearly.

### Business Success

- Findings lead to a prioritized set of practical retention recommendations.
- Recommendations connect a defined customer segment, observed risk, proposed action, and intended outcome.
- Revenue exposure and customer value are incorporated into prioritization where the available data permits.
- Decision-makers can distinguish descriptive insight from predictive risk and causal evidence.

### Product and Presentation Success

- The Streamlit application provides clear executive KPIs, useful filters, intuitive navigation, and concise explanations.
- Dashboard figures remain consistent with the validated analytical results.
- The application runs locally from documented setup instructions and is prepared for online deployment.
- The notebook, dashboard, and README form a coherent, original, and professionally presented portfolio project.

## 1.11 Initial Assumptions and Constraints

- The dataset is treated as a customer-level snapshot rather than a longitudinal record of customer activity.
- Associations will not be described as causal effects unless the available evidence supports that conclusion.
- Churn reasons and categories describe customers who have already churned and will not be used as predictors of future churn.
- Customer status and the churn label directly reveal the outcome and will be excluded from predictive inputs.
- Satisfaction and churn scores require special review because they may contain information collected after churn or derived from the outcome.
- The current data is limited to California and one reported quarter, so geographic and time-based conclusions will be framed accordingly.
- Any estimated campaign benefit will be presented as a scenario, not as guaranteed financial impact.

## Stage 1 Deliverable

The business need is to move from a general awareness of customer attrition to a targeted and commercially relevant retention strategy. This project will identify where churn is concentrated, explain the principal recorded reasons for customer loss, estimate pre-churn risk using appropriate customer information, and recommend segment-specific interventions. Its final Streamlit dashboard will enable executives and operational teams to explore churn exposure, prioritize customers and actions, and evaluate retention scenarios from a consistent evidence base.

---

**Developed and Designed by Emmanuel Onuoha**

# Stage 2 — Dataset Understanding and Data-Quality Audit

This stage examines the structure, meaning, completeness, consistency, and analytical suitability of the supplied customer data before any cleaning, visualization, or modeling decisions are made.

In [1]:
from pathlib import Path

import numpy as np
import pandas as pd

pd.set_option("display.max_columns", None)
pd.set_option("display.max_colwidth", 120)

DATA_PATH = Path("TelcoCustomerChurn.csv")
df = pd.read_csv(DATA_PATH)

print(f"Rows: {df.shape[0]:,}")
print(f"Columns: {df.shape[1]}")
print(f"Approximate memory usage: {df.memory_usage(deep=True).sum() / 1024**2:.2f} MB")

Rows: 7,043
Columns: 50
Approximate memory usage: 11.92 MB


## 2.1 Dataset Source and Coverage

The analysis uses the locally supplied file `TelcoCustomerChurn.csv`. Its structure is consistent with the widely circulated IBM Telco Customer Churn sample, but the precise download URL and licence are not embedded in the CSV. The public portfolio documentation should therefore identify the local file as the immediate source and add the verified original publication link and licence before external release. This avoids presenting an unverified attribution as fact.

| Attribute | Observed value |
|---|---:|
| Customer records | 7,043 |
| Variables | 50 |
| Unique customer IDs | 7,043 |
| Geographic coverage | California, United States |
| Cities represented | 1,106 |
| ZIP codes represented | 1,626 |
| Reported quarter | Q3 only |
| Customer-status classes | Churned, Stayed, Joined |
| Churn target | `ChurnLabel` |

The data behaves like a customer-level snapshot: each row represents one customer, while accumulated charges summarize activity over that customer's tenure. It is not a sequence of repeated monthly observations.

## 2.2 Variable Groups

| Group | Important variables | Purpose |
|---|---|---|
| Identifier | CustomerID | Uniquely identifies a customer; excluded from modeling |
| Demographic and household | Gender, Age, Under30, SeniorCitizen, Married, Dependents, NumberofDependents | Describes the customer and household context |
| Geographic | Country, State, City, ZipCode, Latitude, Longitude, Population | Supports location-based analysis and mapping |
| Engagement and lifecycle | Quarter, ReferredaFriend, Number_of_Referrals, TenureinMonths, Offer | Describes tenure, referrals, and offer participation |
| Telecom services | PhoneService, MultipleLines, InternetService, InternetType, AvgMonthlyLongDistanceCharges, AvgMonthlyGBDownload | Describes core service adoption and usage |
| Add-on services | OnlineSecurity, OnlineBackup, DeviceProtectionPlan, PremiumTechSupport, StreamingTV, StreamingMovies, StreamingMusic, UnlimitedData | Describes service bundles and add-ons |
| Contract and billing | Contract, PaperlessBilling, PaymentMethod, MonthlyCharge | Describes commitment and payment arrangements |
| Financial | TotalCharges, TotalRefunds, TotalExtraDataCharges, TotalLongDistanceCharges, TotalRevenue, CLTV | Describes accumulated revenue, adjustments, and value |
| Experience and model-derived | SatisfactionScore, ChurnScore | Describes satisfaction and a pre-existing churn score; both require leakage/provenance review |
| Outcome | CustomerStatus, ChurnLabel | Records whether a customer joined, stayed, or churned |
| Post-churn diagnostic | ChurnCategory, ChurnReason | Explains recorded reasons after churn; descriptive use only |

## 2.3 Data Dictionary — Customer, Geography, and Lifecycle

| Variable | Data class | Business meaning | Analytical treatment |
|---|---|---|---|
| CustomerID | Identifier | Unique customer reference | Uniqueness check; exclude from model |
| Gender | Categorical | Recorded customer gender | Descriptive and potential predictor; interpret cautiously |
| Age | Numerical | Customer age in years | Validate range; analyze continuously and in bands |
| Under30 | Binary categorical | Indicates whether age is below 30 | Redundant with Age; use one representation in modeling |
| SeniorCitizen | Binary categorical | Indicates whether age is at least 65 | Redundant with Age; useful for business segmentation |
| Married | Binary categorical | Recorded marital status | Segment and potential predictor |
| Dependents | Binary categorical | Indicates whether the customer has dependents | Validate against NumberofDependents |
| NumberofDependents | Discrete numerical | Number of dependents | Validate as non-negative integer |
| Country | Geographic categorical | Customer country | Constant in this file; exclude from model |
| State | Geographic categorical | Customer state | Constant in this file; exclude from model |
| City | Geographic categorical | Customer city | Geographic analysis; high-cardinality modeling requires care |
| ZipCode | Geographic identifier | Five-digit service-area ZIP code | Treat as categorical/text, not a measurable number |
| Latitude | Geographic numerical | Latitude associated with the service location | Mapping only unless a justified spatial feature is developed |
| Longitude | Geographic numerical | Longitude associated with the service location | Mapping only unless a justified spatial feature is developed |
| Population | Numerical | Population associated with the customer's ZIP-code area | Contextual geographic feature; not the customer's household size |
| Quarter | Time categorical | Reported quarter for the record | Constant at Q3; cannot support trend analysis |
| ReferredaFriend | Binary categorical | Whether the customer referred another person | Validate against referral count |
| Number_of_Referrals | Discrete numerical | Number of customer referrals | Non-negative engagement measure |
| TenureinMonths | Discrete numerical | Months the customer has been with the company | Core lifecycle measure; create interpretable tenure bands |
| Offer | Categorical | Promotional offer assigned or accepted in the source data | Missing means no recorded offer; recode explicitly as No Offer after validation |

## 2.4 Data Dictionary — Services, Billing, and Financials

| Variable | Data class | Business meaning | Analytical treatment |
|---|---|---|---|
| PhoneService | Binary categorical | Whether phone service is active | Service indicator |
| AvgMonthlyLongDistanceCharges | Continuous numerical | Average monthly long-distance charges | Zero is valid for customers without phone service |
| MultipleLines | Binary categorical | Whether multiple phone lines are active | Service indicator |
| InternetService | Binary categorical | Whether internet service is active | Validates InternetType and download usage |
| InternetType | Categorical | DSL, cable, or fiber-optic connection | Blank is structurally not applicable when InternetService is No |
| AvgMonthlyGBDownload | Numerical | Average monthly internet data downloaded in GB | Zero is valid for customers without internet |
| OnlineSecurity | Binary categorical | Subscription to online security | Add-on service indicator |
| OnlineBackup | Binary categorical | Subscription to online backup | Add-on service indicator |
| DeviceProtectionPlan | Binary categorical | Subscription to device protection | Add-on service indicator |
| PremiumTechSupport | Binary categorical | Subscription to premium technical support | Add-on service indicator |
| StreamingTV | Binary categorical | Subscription to streaming television | Add-on service indicator |
| StreamingMovies | Binary categorical | Subscription to streaming movies | Add-on service indicator |
| StreamingMusic | Binary categorical | Subscription to streaming music | Add-on service indicator |
| UnlimitedData | Binary categorical | Whether the internet plan includes unlimited data | Plan indicator |
| Contract | Ordinal categorical | Month-to-month, one-year, or two-year agreement | Core commitment and churn-segmentation variable |
| PaperlessBilling | Binary categorical | Whether billing is paperless | Billing preference indicator |
| PaymentMethod | Categorical | Bank withdrawal, credit card, or mailed check | Billing and churn-segmentation variable |
| MonthlyCharge | Continuous numerical | Current recurring monthly charge | Validate as non-negative; analyze with service mix |
| TotalCharges | Continuous numerical | Accumulated core service charges | Non-negative; affected by tenure and historical billing changes |
| TotalRefunds | Continuous numerical | Accumulated refunds issued | Zero is valid; subtracts from revenue |
| TotalExtraDataCharges | Continuous numerical | Accumulated excess-data charges | Zero is valid |
| TotalLongDistanceCharges | Continuous numerical | Accumulated long-distance charges | Zero is valid without phone service |
| TotalRevenue | Continuous numerical | Net accumulated revenue from the customer | Verified as charges plus long-distance and extra-data charges minus refunds |

## 2.5 Data Dictionary — Experience, Value, and Churn Outcomes

| Variable | Data class | Business meaning | Analytical treatment |
|---|---|---|---|
| SatisfactionScore | Ordinal numerical | Recorded satisfaction score from 1 to 5 | Descriptive use; exclude from baseline model until timing and provenance are confirmed |
| CustomerStatus | Outcome categorical | Joined, Stayed, or Churned status | Outcome-revealing; never use as a churn predictor |
| ChurnLabel | Binary target | Yes when the customer churned; No otherwise | Primary target for churn analysis and modeling |
| ChurnScore | Model-derived numerical | Existing score from 5 to 96 associated with churn risk | Exclude from the new model to avoid circularity and leakage |
| CLTV | Numerical | Estimated customer lifetime value | Use for commercial prioritization; model use requires provenance review |
| ChurnCategory | Post-churn categorical | Broad recorded category explaining why a churned customer left | Diagnostic analysis of churners only; never a pre-churn predictor |
| ChurnReason | Post-churn categorical | Specific recorded reason for leaving | Diagnostic analysis of churners only; never a pre-churn predictor |

In [2]:
audit_summary = pd.Series({
    "Rows": len(df),
    "Columns": df.shape[1],
    "Duplicate rows": int(df.duplicated().sum()),
    "Duplicate customer IDs": int(df["CustomerID"].duplicated().sum()),
    "Missing customer IDs": int(df["CustomerID"].isna().sum()),
    "Columns containing nulls": int(df.isna().any().sum()),
    "Constant columns": int((df.nunique(dropna=False) == 1).sum()),
})

missing_summary = (
    df.isna().sum()
      .loc[lambda values: values.gt(0)]
      .rename("MissingCount")
      .to_frame()
)
missing_summary["MissingPercent"] = (missing_summary["MissingCount"] / len(df) * 100).round(2)

display(audit_summary.to_frame("Value"))
display(missing_summary.sort_values("MissingCount", ascending=False))

,Value
Rows,7043
Columns,50
Duplicate rows,0
Duplicate customer IDs,0
Missing customer IDs,0
Columns containing nulls,4
Constant columns,3


,MissingCount,MissingPercent
ChurnCategory,5174,73.46
ChurnReason,5174,73.46
Offer,3877,55.05
InternetType,1526,21.67


## 2.6 Completeness and Duplicate Assessment

No duplicate rows, duplicate customer IDs, or missing customer IDs were found. All 7,043 rows therefore represent distinct customer records based on `CustomerID`.

| Variable | Missing count | Missing rate | Interpretation and treatment |
|---|---:|---:|---|
| ChurnCategory | 5,174 | 73.46% | Structurally unavailable for all non-churned customers; retain for churn-reason analysis only |
| ChurnReason | 5,174 | 73.46% | Structurally unavailable for all non-churned customers; retain for churn-reason analysis only |
| Offer | 3,877 | 55.05% | Represents no recorded offer; recode to an explicit `No Offer` category for clarity |
| InternetType | 1,526 | 21.67% | Not applicable for exactly the 1,526 customers without internet service; recode to `No Internet` |

These blanks should not be filled with statistical estimates. They encode business states and will be converted to explicit categories where appropriate. No other column contains a null value.

In [3]:
yes_no_columns = [
    "Under30", "SeniorCitizen", "Married", "Dependents",
    "ReferredaFriend", "PhoneService", "MultipleLines",
    "InternetService", "OnlineSecurity", "OnlineBackup",
    "DeviceProtectionPlan", "PremiumTechSupport", "StreamingTV",
    "StreamingMovies", "StreamingMusic", "UnlimitedData",
    "PaperlessBilling", "ChurnLabel"
]

invalid_yes_no = {
    column: sorted(set(df[column].dropna()) - {"Yes", "No"})
    for column in yes_no_columns
}
invalid_yes_no = {column: values for column, values in invalid_yes_no.items() if values}

consistency_checks = pd.Series({
    "Under30 disagrees with Age": int(((df["Age"] < 30) != df["Under30"].eq("Yes")).sum()),
    "SeniorCitizen disagrees with Age >= 65": int(((df["Age"] >= 65) != df["SeniorCitizen"].eq("Yes")).sum()),
    "Dependents disagrees with dependent count": int(((df["NumberofDependents"] > 0) != df["Dependents"].eq("Yes")).sum()),
    "Referral flag disagrees with referral count": int(((df["Number_of_Referrals"] > 0) != df["ReferredaFriend"].eq("Yes")).sum()),
    "No phone service but non-zero long-distance average": int(((df["PhoneService"] == "No") & df["AvgMonthlyLongDistanceCharges"].ne(0)).sum()),
    "No internet but non-zero download usage": int(((df["InternetService"] == "No") & df["AvgMonthlyGBDownload"].ne(0)).sum()),
    "No internet but internet type present": int(((df["InternetService"] == "No") & df["InternetType"].notna()).sum()),
    "Internet customer with missing internet type": int(((df["InternetService"] == "Yes") & df["InternetType"].isna()).sum()),
    "CustomerStatus disagrees with ChurnLabel": int(((df["CustomerStatus"] == "Churned") != df["ChurnLabel"].eq("Yes")).sum()),
    "Non-churner has churn details": int(((df["ChurnLabel"] == "No") & (df["ChurnCategory"].notna() | df["ChurnReason"].notna())).sum()),
    "Churner is missing churn details": int(((df["ChurnLabel"] == "Yes") & (df["ChurnCategory"].isna() | df["ChurnReason"].isna())).sum()),
})

revenue_recalculated = (
    df["TotalCharges"]
    + df["TotalLongDistanceCharges"]
    + df["TotalExtraDataCharges"]
    - df["TotalRefunds"]
)

print("Invalid Yes/No values:", invalid_yes_no or "None")
display(consistency_checks.to_frame("FailedRecords"))
print("Maximum TotalRevenue reconciliation difference:",
      round((df["TotalRevenue"] - revenue_recalculated).abs().max(), 10))

Invalid Yes/No values: None


,FailedRecords
Under30 disagrees with Age,0
SeniorCitizen disagrees with Age >= 65,0
Dependents disagrees with dependent count,0
Referral flag disagrees with referral count,0
No phone service but non-zero long-distance average,0
No internet but non-zero download usage,0
No internet but internet type present,0
Internet customer with missing internet type,0
CustomerStatus disagrees with ChurnLabel,0
Non-churner has churn details,0


Maximum TotalRevenue reconciliation difference: 0.0


## 2.7 Validity and Consistency Findings

The principal integrity checks returned no failed records:

- All designated binary variables contain only `Yes` and `No`.
- Age ranges from 19 to 80; tenure ranges from 1 to 72 months; satisfaction ranges from 1 to 5; and ChurnScore ranges from 5 to 96.
- No monetary, count, usage, population, or tenure field contains an invalid negative value. Negative longitude is geographically valid for California.
- `Under30` agrees with Age below 30 in every record.
- `SeniorCitizen` agrees with Age of at least 65 in every record.
- The dependent and referral indicator fields agree with their corresponding counts.
- Customers without phone service have zero average and total long-distance charges.
- Customers without internet service have zero download usage and no recorded internet type.
- Every internet customer has a recorded internet type.
- `CustomerStatus` and `ChurnLabel` agree for every customer.
- Every churned customer has both a churn category and reason, while no non-churned customer has either.
- All ZIP codes contain five digits, and all latitude and longitude values fall within valid global coordinate ranges.
- `TotalRevenue` reconciles with `TotalCharges + TotalLongDistanceCharges + TotalExtraDataCharges - TotalRefunds`, apart from negligible floating-point precision.

`TotalCharges` does not always equal current `MonthlyCharge × TenureinMonths`. This is not automatically an error: current monthly prices, prorating, service changes, and billing adjustments can cause historical accumulated charges to differ from that simple estimate. The field will be retained and interpreted as the supplied accumulated charge.

## 2.8 Constant, Redundant, and High-Cardinality Fields

- `Country`, `State`, and `Quarter` each contain one value only. They provide context but no within-dataset explanatory or predictive variation.
- `Under30` and `SeniorCitizen` are exact age-derived indicators. `Dependents` and `ReferredaFriend` are likewise derivable from their count variables. Retaining both versions is helpful for reporting, but using all of them together may add redundancy to a model.
- `CustomerID` is unique and carries no intended behavioral meaning. It will be retained for lookup but excluded from predictive features.
- `City` and `ZipCode` have high cardinality relative to the dataset size. They are useful for maps and aggregated hotspot analysis, but naive one-hot encoding could create sparse, unstable model features.
- Latitude, longitude, and ZIP-code population describe service-area context rather than an individual customer's behavior and must not be interpreted as personal attributes.

## 2.9 Outcome Timing and Leakage Classification

| Classification | Variables | Use |
|---|---|---|
| Primary target | ChurnLabel | Defines the binary modeling outcome |
| Direct outcome leakage | CustomerStatus | Exclude from predictive inputs because it directly identifies churn |
| Post-churn information | ChurnCategory, ChurnReason | Use only to explain completed churn events |
| Existing model output | ChurnScore | Exclude from the new model; otherwise the project would model another model's score |
| Timing/provenance uncertain | SatisfactionScore | Use descriptively; exclude from the baseline model until it is confirmed that the score was available before churn |
| Derived commercial estimate | CLTV | Use to prioritize value; test separately in modeling only after its calculation timing is understood |
| Candidate pre-churn information | Demographics, tenure, services, contract, billing, charges, referrals, and geography | Eligible subject to preprocessing, fairness, redundancy, and availability checks |

This classification prevents target leakage and keeps the eventual model aligned with the real decision point: identifying risk before a customer has already left.

## 2.10 Dataset Limitations

1. **Single snapshot:** the data contains one row per customer rather than monthly event history, limiting temporal and behavioral change analysis.
2. **Single quarter:** all records are marked Q3, so quarterly trends, seasonality, and changes in churn over time cannot be measured.
3. **Restricted geography:** all records are from California, so results should not be generalized automatically to other markets.
4. **No churn date:** the exact timing of churn and time-to-event behavior cannot be studied.
5. **No interaction history:** calls, complaints, outages, support tickets, campaign contacts, and resolution times are unavailable.
6. **No acquisition or campaign cost:** retention profitability can only be illustrated through transparent scenarios, not measured as realized return on investment.
7. **Outcome-dependent reason fields:** churn categories and reasons are available only after departure and cannot support pre-churn prediction.
8. **Unverified provenance for derived scores:** ChurnScore, SatisfactionScore, and CLTV require documentation of their calculation and timing before predictive use.
9. **Observational data:** relationships may reflect confounding factors and should not be described as causal effects.
10. **Source attribution pending verification:** the immediate source is the supplied CSV; the original publisher URL and licence must be confirmed before public distribution.

## 2.11 Data-Quality Report and Recommended Actions

| Quality dimension | Assessment | Recommended action |
|---|---|---|
| Uniqueness | Pass | Retain one record per CustomerID |
| Completeness | Pass with structural blanks | Recode Offer and InternetType blanks explicitly; restrict churn details to churners |
| Validity | Pass | Preserve valid ranges and zero values; treat ZIP code as categorical |
| Internal consistency | Pass | Retain automated checks in the preparation workflow |
| Target integrity | Pass | Use ChurnLabel as target and CustomerStatus for descriptive reporting only |
| Predictive suitability | Conditional pass | Remove leakage, constant, identifier, and unjustified derived variables |
| Geographic suitability | Suitable for California analysis | Apply minimum segment sizes and avoid national generalization |
| Temporal suitability | Limited | Do not present quarter-over-quarter trends |
| Source documentation | Requires confirmation | Add verified publisher URL and licence before public deployment |

### Overall Assessment

The dataset is structurally clean and suitable for descriptive churn analysis, customer segmentation, and a carefully controlled predictive exercise. No rows need to be deleted for duplication or invalidity. The next preparation stage should focus on explicit category labeling, analytical data types, feature redundancy, model leakage controls, and documented feature engineering—not aggressive correction or statistical imputation.

---

**Developed and Designed by Emmanuel Onuoha**

# Stage 3 — Business KPI Framework

This stage defines the project's decision metrics before visualization and modeling. Each KPI has a fixed business meaning, population, formula, display convention, and interpretation so that the notebook, dashboard, and README report consistent values.

## 3.1 Measurement Principles

1. `CustomerID` is the counting unit; each customer is counted once.
2. `ChurnLabel` defines the binary churn outcome.
3. `CustomerStatus` separates non-churned customers into `Stayed` and `Joined`.
4. Rates always state their eligible denominator.
5. Stock measures, recurring monthly amounts, accumulated revenue, and estimated lifetime value are reported separately.
6. Historical revenue from churned customers is not described as revenue lost.
7. High-risk counts will be based on the project's validated model and operating threshold—not the supplied `ChurnScore`.
8. Dashboard filters must recompute numerators and denominators from the same filtered customer population.

In [4]:
# Boolean masks create one consistent definition for every downstream KPI.
is_churned = df["ChurnLabel"].eq("Yes")
is_stayed = df["CustomerStatus"].eq("Stayed")
is_joined = df["CustomerStatus"].eq("Joined")
is_active = ~is_churned

total_customers = df["CustomerID"].nunique()
churned_customers = int(is_churned.sum())
stayed_customers = int(is_stayed.sum())
new_customers = int(is_joined.sum())
active_customers = int(is_active.sum())

kpi_values = {
    "Total customers": total_customers,
    "Churned customers": churned_customers,
    "Retained / stayed customers": stayed_customers,
    "New / joined customers": new_customers,
    "Active customers": active_customers,
    "Overall churn rate": churned_customers / total_customers,
    "Portfolio non-churn rate": active_customers / total_customers,
    "Established-customer retention rate": stayed_customers / (stayed_customers + churned_customers),
    "Average monthly charge": df["MonthlyCharge"].mean(),
    "Average tenure (months)": df["TenureinMonths"].mean(),
    "Churned-customer accumulated revenue": df.loc[is_churned, "TotalRevenue"].sum(),
    "Churned-customer monthly revenue exposure": df.loc[is_churned, "MonthlyCharge"].sum(),
    "Average customer lifetime value": df["CLTV"].mean(),
    "Churned-customer CLTV": df.loc[is_churned, "CLTV"].sum(),
}

pd.Series(kpi_values, name="Value").to_frame()

,Value
Total customers,7.043000e+03
Churned customers,1.869000e+03
Retained / stayed customers,4.720000e+03
New / joined customers,4.540000e+02
Active customers,5.174000e+03
Overall churn rate,2.653699e-01
Portfolio non-churn rate,7.346301e-01
Established-customer retention rate,7.163454e-01
Average monthly charge,6.476169e+01
Average tenure (months),3.238677e+01


## 3.2 Customer and Churn KPIs

| KPI | Definition and formula | Eligible population | Baseline value | Display |
|---|---|---|---:|---|
| Total Customers | Distinct count of `CustomerID` | All records | 7,043 | Whole number |
| Churned Customers | Customers where `ChurnLabel = Yes` | All customers | 1,869 | Whole number |
| Retained / Stayed Customers | Customers where `CustomerStatus = Stayed` | All customers | 4,720 | Whole number |
| New Customers | Customers where `CustomerStatus = Joined` | All customers | 454 | Whole number |
| Active Customers | Customers who have not churned; Stayed + Joined | All customers | 5,174 | Whole number |
| Overall Churn Rate | Churned Customers ÷ Total Customers | All customers | 26.54% | Percentage, two decimals |
| Portfolio Non-Churn Rate | Active Customers ÷ Total Customers | All customers | 73.46% | Percentage, two decimals |
| Established-Customer Retention Rate | Stayed ÷ (Stayed + Churned) | Customers with Stayed or Churned status; Joined excluded | 71.63% | Percentage, two decimals |

The portfolio non-churn rate and established-customer retention rate answer different questions. The first describes the full snapshot and is exactly `100% − churn rate`. The second excludes newly joined customers because they have not yet demonstrated retention. The dashboard must label them separately rather than using the generic term *retention rate* without explanation.

## 3.3 Customer Experience and Commercial KPIs

| KPI | Definition and formula | Baseline value | Interpretation |
|---|---|---:|---|
| Average Monthly Charge | Mean of `MonthlyCharge` across distinct customers | $64.76 | Average current recurring charge per customer |
| Average Tenure | Mean of `TenureinMonths` | 32.39 months | Average observed customer relationship length |
| Churned-Customer Accumulated Revenue | Sum of `TotalRevenue` for churned customers | $3,684,459.82 | Revenue historically generated by customers who later churned; not equivalent to revenue lost |
| Churned-Customer Monthly Revenue Exposure | Sum of `MonthlyCharge` for churned customers | $139,130.85 per month | Snapshot of recurring monthly charges associated with churners; not realized monthly loss without churn-date evidence |
| Average Customer Lifetime Value | Mean of `CLTV` for all customers | $4,400.30 | Average supplied estimate of customer value; calculation method requires source documentation |
| Churned-Customer CLTV | Sum of `CLTV` for churned customers | $7,755,256 | Value-prioritization indicator for the churned segment; should not be interpreted as fully recoverable loss |

For diagnostic comparisons, churned customers currently average $74.44 in monthly charges and 17.98 months of tenure, compared with overall averages of $64.76 and 32.39 months. These comparisons are supporting measures rather than primary executive KPIs.

## 3.4 High-Risk Customer KPI

**Definition:** the number of currently active customers whose predicted churn probability is greater than or equal to the project's approved intervention threshold.

**Formula:** Count of active customers where `PredictedChurnProbability ≥ ApprovedThreshold`.

**Current value:** 947 active customers at the validated 0.32 operating threshold established in Stage 11.

The threshold will be selected using validation results, the relative cost of missed churners and unnecessary interventions, and the retention team's campaign capacity. The supplied `ChurnScore` will not be used to populate this KPI because its derivation is unknown and using it would undermine the independence of the project's model. Until modeling is complete, dashboards may display descriptive **priority segments**, but they must not label individual active customers as model-predicted high risk.

## 3.5 Filter and Aggregation Rules

- Customer counts use distinct `CustomerID`, even if future source files contain repeated records.
- Churn rates use the filtered customer count as denominator unless explicitly labelled otherwise.
- Established-customer retention always excludes `Joined` customers from both numerator and denominator.
- Averages are customer-weighted means; they are not averages of previously aggregated group averages.
- Currency values use US-dollar formatting because the dataset represents customers in the United States.
- Dashboard percentages display two decimal places; currency cards display two decimals and thousands separators.
- When a filter produces no eligible records, the metric should display `Not available` rather than zero.
- Geographic comparisons will show customer counts alongside rates and apply a minimum sample-size warning.
- KPI cards will state whether they represent current stock, monthly exposure, accumulated history, or estimated lifetime value.

In [5]:
# Reconciliation tests protect KPI definitions from silent changes.
assert total_customers == len(df) == 7_043
assert churned_customers + active_customers == total_customers
assert stayed_customers + new_customers == active_customers
assert churned_customers == 1_869
assert stayed_customers == 4_720
assert new_customers == 454
assert np.isclose(churned_customers / total_customers, 0.2653698708)
assert np.isclose(df.loc[is_churned, "TotalRevenue"].sum(), 3_684_459.82)

print("All KPI reconciliation checks passed.")

All KPI reconciliation checks passed.


## Stage 3 Deliverable — KPI Framework

The project now has a governed KPI framework that separates churn, active-customer status, established-customer retention, recurring monthly exposure, accumulated revenue, and estimated lifetime value. Each metric has a reproducible definition and an explicit eligible population. The high-risk customer count is deliberately deferred until an independent model and an operational decision threshold have been validated. This framework will serve as the single source of truth for all notebook findings and Streamlit dashboard cards.

---

**Developed and Designed by Emmanuel Onuoha**

# Stage 4 — Data Cleaning and Preparation

This stage converts the validated source data into a consistent analytical dataset while preserving every customer record and leaving the original CSV unchanged. The preparation logic is maintained in `src/data_preparation.py` so the notebook and future Streamlit application use the same rules.

## 4.1 Cleaning Strategy

The Stage 2 audit found no corrupted, duplicated, or unjustifiably incomplete customer records. Cleaning therefore focuses on consistency and analytical usability rather than deleting observations or statistically imputing business states.

The preparation workflow will:

1. Validate the complete 50-column input schema.
2. Reject missing or duplicated customer identifiers.
3. Re-run domain, range, relationship, and revenue-reconciliation checks.
4. Rename fields to consistent `snake_case`.
5. Convert structural blanks to explicit, interpretable categories.
6. Preserve customer and ZIP identifiers as strings.
7. Assign categorical data types in memory.
8. Add transparent binary churn and active-status flags.
9. Confirm that no nulls remain and that row count and identifier uniqueness are unchanged.
10. Export a reproducible clean CSV for analysis and application development.

In [6]:
from src.data_preparation import (
    COLUMN_NAMES,
    MODEL_EXCLUDED_COLUMNS,
    build_clean_dataset,
    validate_raw_data,
)

RAW_DATA_PATH = Path("TelcoCustomerChurn.csv")
CLEAN_DATA_PATH = Path("data/processed/telco_customer_churn_clean.csv")

raw_df = pd.read_csv(RAW_DATA_PATH)
validate_raw_data(raw_df)
clean_df, clean_file = build_clean_dataset(RAW_DATA_PATH, CLEAN_DATA_PATH)

print(f"Raw shape: {raw_df.shape}")
print(f"Clean shape: {clean_df.shape}")
print(f"Clean file: {clean_file}")

Raw shape: (7043, 50)
Clean shape: (7043, 52)
Clean file: D:\Data Analysis\Executive Portfolios\Customer Churn\Customer Churn\data\processed\telco_customer_churn_clean.csv


## 4.2 Column-Name Standardization

All source fields are renamed consistently without changing their business meaning. Examples include:

| Source name | Prepared name |
|---|---|
| CustomerID | customer_id |
| SeniorCitizen | senior_citizen |
| NumberofDependents | number_of_dependents |
| Number_of_Referrals | number_of_referrals |
| TenureinMonths | tenure_in_months |
| AvgMonthlyGBDownload | avg_monthly_gb_download |
| DeviceProtectionPlan | device_protection_plan |
| MonthlyCharge | monthly_charge |
| TotalLongDistanceCharges | total_long_distance_charges |
| CustomerStatus | customer_status |
| ChurnLabel | churn_label |
| ChurnReason | churn_reason |

The complete one-to-one mapping is stored in the reusable `COLUMN_NAMES` dictionary. No original field is silently discarded during renaming.

## 4.3 Structural Missing-Value Treatment

| Prepared field | Source blank means | Explicit replacement | Reason |
|---|---|---|---|
| offer | No recorded promotional offer | `No Offer` | Preserves a meaningful comparison group |
| internet_type | Customer does not have internet service | `No Internet` | Distinguishes non-applicability from unknown data |
| churn_category | Customer did not churn | `Not Applicable` | Prevents structural absence from appearing as a data-quality defect |
| churn_reason | Customer did not churn | `Not Applicable` | Keeps post-churn detail explicitly restricted to churners |

No mean, median, mode, forward-fill, or model-based imputation is applied because the blanks encode known business conditions. After these replacements, the prepared dataset contains no null values.

## 4.4 Data-Type Treatment

- `customer_id` is stored as text because it is an identifier, not a measurable quantity.
- `zip_code` is converted to a five-character string so leading zeroes would be preserved in future data.
- Yes/No, nominal, ordinal-label, geographic-label, outcome-label, and reason fields use categorical dtype in memory.
- Counts remain integer-valued; charges, refunds, revenue, and coordinates retain their numerical precision.
- No numerical scaling or categorical encoding is performed at this stage. Those operations belong inside the future modeling pipeline to prevent training/test contamination.
- The exported CSV stores values rather than pandas-specific category metadata; data types are reapplied through the preparation function whenever the project loads raw data.

## 4.5 Added Helper Fields

Two transparent fields are added for reliable aggregation:

| Field | Definition | Values | Intended use |
|---|---|---|---|
| churn_flag | 1 when churn_label is Yes; otherwise 0 | 0 or 1 | Churn counts and rates |
| active_flag | 1 when churn_label is No; otherwise 0 | 0 or 1 | Active-customer counts |

These fields do not introduce new information. They are auditable numeric representations of the existing outcome and will never be included among predictive input features. Business feature engineering—such as tenure bands, service counts, and customer-value segments—will be handled separately so raw cleaning remains distinguishable from analytical feature creation.

In [7]:
preparation_checks = pd.Series({
    "Rows preserved": len(clean_df) == len(raw_df),
    "Source columns all mapped": set(raw_df.columns) == set(COLUMN_NAMES),
    "Prepared names unique": len(clean_df.columns) == len(set(clean_df.columns)),
    "Customer IDs complete": clean_df["customer_id"].notna().all(),
    "Customer IDs unique": clean_df["customer_id"].nunique() == len(clean_df),
    "No remaining nulls": not clean_df.isna().any().any(),
    "ZIP codes have five characters": clean_df["zip_code"].str.len().eq(5).all(),
    "Churn flag reconciles": clean_df["churn_flag"].sum() == 1_869,
    "Active flag reconciles": clean_df["active_flag"].sum() == 5_174,
    "Customer count reconciles": clean_df["customer_id"].nunique() == 7_043,
    "Clean export exists": CLEAN_DATA_PATH.exists(),
})

display(preparation_checks.to_frame("Passed"))
assert preparation_checks.all(), "At least one preparation check failed."

,Passed
Rows preserved,True
Source columns all mapped,True
Prepared names unique,True
Customer IDs complete,True
Customer IDs unique,True
No remaining nulls,True
ZIP codes have five characters,True
Churn flag reconciles,True
Active flag reconciles,True
Customer count reconciles,True


## 4.6 Modeling-Safety Preparation

Cleaning does not mean every clean field is eligible for prediction. The following fields remain in the analytical dataset for reporting but are placed on the modeling exclusion list:

- `customer_id`: identifier
- `country`, `state`, and `quarter`: constant fields
- `customer_status`: directly reveals churn
- `churn_label`: modeling target, stored separately
- `churn_flag` and `active_flag`: numeric restatements of the target
- `churn_score`: pre-existing model output
- `churn_category` and `churn_reason`: post-churn information
- `satisfaction_score`: excluded from the baseline until collection timing is verified
- `cltv`: initially reserved for value prioritization until calculation provenance is verified

Geographic identifiers and redundant age, dependent, and referral fields will receive additional feature-selection treatment during modeling.

## 4.7 Preparation Outcome

| Measure | Raw data | Prepared data |
|---|---:|---:|
| Customer rows | 7,043 | 7,043 |
| Source variables retained | 50 | 50 |
| Helper fields added | 0 | 2 |
| Duplicate customer IDs | 0 | 0 |
| Columns containing blanks | 4 | 0 |
| Output file | `TelcoCustomerChurn.csv` | `data/processed/telco_customer_churn_clean.csv` |

No customer records were deleted, no outliers were silently capped, and no unknown values were fabricated. The preparation process is deterministic: the same valid source file will produce the same clean analytical data.

## Stage 4 Deliverable — Clean Analytical Dataset

The project now has a validated, reusable preparation pipeline and a clean analytical dataset containing 7,043 unique customers, 50 standardized source variables, and two transparent aggregation flags. Structural blanks have been converted into explicit business categories, identifiers have appropriate representations, and modeling exclusions have been documented before feature engineering begins.

---

**Developed and Designed by Emmanuel Onuoha**

# Stage 5 — Business Feature Engineering

This stage translates detailed source fields into consistent, executive-friendly customer segments. Feature logic is implemented in `src/feature_engineering.py` and produces a separate feature-enhanced dataset without changing the clean or raw files.

In [8]:
from src.feature_engineering import (
    COUNTED_SERVICES,
    FEATURE_COLUMNS,
    PROTECTION_SUPPORT_SERVICES,
    build_feature_dataset,
)

FEATURE_DATA_PATH = Path("data/processed/telco_customer_churn_features.csv")
feature_df, feature_file = build_feature_dataset(CLEAN_DATA_PATH, FEATURE_DATA_PATH)

print(f"Feature-enhanced shape: {feature_df.shape}")
print(f"Features added: {len(FEATURE_COLUMNS)}")
print(f"Feature file: {feature_file}")

Feature-enhanced shape: (7043, 64)
Features added: 12
Feature file: D:\Data Analysis\Executive Portfolios\Customer Churn\Customer Churn\data\processed\telco_customer_churn_features.csv


## 5.1 Feature Catalogue

| Feature | Definition | Business purpose |
|---|---|---|
| tenure_group | Tenure grouped into 1–6, 7–12, 13–24, 25–48, and 49–72 months | Identifies lifecycle and onboarding risk |
| age_group | Age grouped into 19–29, 30–44, 45–59, 60–69, and 70+ | Makes demographic comparisons interpretable |
| monthly_charge_band | Monthly charge grouped into Under $35, $35–$69.99, $70–$89.99, and $90+ | Compares price exposure using stable business bands |
| customer_value_segment | CLTV grouped into Emerging, Core, High, and Premium value using fixed portfolio quartiles | Prioritizes commercially important customers |
| service_count | Count of ten core and add-on services marked Yes | Summarizes product adoption |
| protection_support_service_count | Count of online security, online backup, device protection, and premium support | Measures adoption of retention-associated support services |
| referral_group | Referral count grouped into none, 1–2, 3–5, and 6+ | Measures advocacy intensity |
| contract_risk_group | Descriptive commitment label derived from contract duration | Communicates observed contract exposure |
| descriptive_risk_points | Count of five transparent, pre-churn risk indicators | Supports explainable descriptive prioritization |
| descriptive_risk_segment | Lower, Elevated, High, or Very High based on descriptive risk points | Creates an interim business segment—not a prediction |
| avg_revenue_per_tenure_month | Total revenue divided by tenure in months | Normalizes accumulated revenue for relationship length |
| customer_engagement_profile | Hierarchical profile based on referrals, protection/support adoption, and service count | Creates intuitive engagement groups for the dashboard |

## 5.2 Lifecycle, Demographic, and Charge Bands

### Tenure Group

- **1–6 months:** initial onboarding and early experience
- **7–12 months:** remainder of the first year
- **13–24 months:** developing relationship
- **25–48 months:** established relationship
- **49–72 months:** long-standing relationship

### Age Group

The five age bands retain detail among older customers because the data-quality audit found substantially different churn exposure above age 60. Age segmentation supports monitoring and tailored service design; it should not be used to justify unfair denial of service or benefits.

### Monthly-Charge Band

Fixed thresholds are used instead of recalculating quantiles so a customer's band remains stable when dashboard filters change or new records are scored. These groups describe charge levels; they do not prove that price causes churn.

## 5.3 Customer-Value Segment

The supplied CLTV measure is segmented using the full portfolio's Stage 2 quartile thresholds:

| Segment | CLTV rule | Customers |
|---|---:|---:|
| Emerging Value | Below $3,469 | 1,760 |
| Core Value | $3,469 to below $4,527 | 1,761 |
| High Value | $4,527 to below $5,380.50 | 1,761 |
| Premium Value | $5,380.50 and above | 1,761 |

The thresholds are fixed in the feature pipeline. `customer_value_segment` is intended for commercial prioritization and dashboard analysis. Because the source does not document when or how CLTV was calculated, this derived segment is excluded from the baseline churn model until provenance is established.

## 5.4 Service-Adoption Features

`service_count` counts the following ten active services: phone, internet, online security, online backup, device protection, premium technical support, streaming TV, streaming movies, streaming music, and unlimited data. Multiple phone lines are treated as a configuration of phone service rather than an additional service.

`protection_support_service_count` is a focused count from zero to four covering online security, online backup, device protection, and premium technical support. Keeping it separate helps assess whether deeper protection and support adoption is associated with retention.

Both features count explicit `Yes` values. They do not infer service adoption from charges or fill absent services.

## 5.5 Referral and Engagement Features

Referral groups distinguish customers with no referrals, 1–2 referrals, 3–5 referrals, and 6 or more referrals.

The engagement profile uses a documented hierarchy so each customer belongs to exactly one group:

1. **Advocate:** has made at least one referral.
2. **Protection Engaged:** no referral, but at least two protection/support services.
3. **Multi-Service:** no referral, fewer than two protection/support services, and at least five counted services.
4. **Basic Relationship:** all remaining customers.

These labels summarize observable adoption and advocacy. They are not psychological assessments and should be interpreted alongside tenure, contract, and internet type.

## 5.6 Contract and Descriptive Risk Segments

Contract risk communicates the dataset's observed commitment pattern:

- Month-to-month → Higher Contract Risk
- One year → Moderate Contract Risk
- Two year → Lower Contract Risk

The descriptive risk score assigns one point for each transparent condition:

- Month-to-month contract
- Tenure of 12 months or less
- Fiber-optic internet
- No premium technical support
- Monthly charge of at least $90

| Points | Descriptive segment | Customers | Observed churn rate | Active customers |
|---:|---|---:|---:|---:|
| 0–1 | Lower | 2,317 | 4.40% | 2,215 |
| 2 | Elevated | 1,527 | 16.63% | 1,273 |
| 3 | High | 1,984 | 35.08% | 1,288 |
| 4–5 | Very High | 1,215 | 67.24% | 398 |

This is a **rule-based descriptive segment**, developed to make known patterns navigable before modeling. It is not the Stage 3 High-Risk Customer KPI, not a calibrated probability, and not a substitute for out-of-sample model validation. It may be shown in exploratory dashboards only with that distinction visible.

## 5.7 Revenue-per-Month Estimate

`avg_revenue_per_tenure_month = total_revenue ÷ tenure_in_months`

This feature normalizes accumulated net revenue for the length of the customer relationship. It includes the source definition of total revenue: core charges, long-distance charges, and extra-data charges, less refunds. It is different from `monthly_charge`, which represents the customer's current recurring charge.

Tenure is at least one month for every customer, so division by zero does not occur. Values are rounded to two decimal places for business presentation. The portfolio average is $88.12 per tenure month, with observed values ranging from $18.17 to $190.70.

In [9]:
feature_validation = pd.Series({
    "Customer rows preserved": len(feature_df) == len(clean_df) == 7_043,
    "Original clean columns preserved": set(clean_df.columns).issubset(feature_df.columns),
    "Twelve features added": len(FEATURE_COLUMNS) == 12,
    "Expected final column count": feature_df.shape[1] == 64,
    "Engineered features complete": not feature_df[FEATURE_COLUMNS].isna().any().any(),
    "Service counts valid": feature_df["service_count"].between(0, 10).all(),
    "Protection/support counts valid": feature_df["protection_support_service_count"].between(0, 4).all(),
    "Risk points valid": feature_df["descriptive_risk_points"].between(0, 5).all(),
    "Revenue-per-month positive": feature_df["avg_revenue_per_tenure_month"].gt(0).all(),
    "Feature export exists": FEATURE_DATA_PATH.exists(),
})

display(feature_validation.to_frame("Passed"))
assert feature_validation.all(), "At least one feature validation failed."

,Passed
Customer rows preserved,True
Original clean columns preserved,True
Twelve features added,True
Expected final column count,True
Engineered features complete,True
Service counts valid,True
Protection/support counts valid,True
Risk points valid,True
Revenue-per-month positive,True
Feature export exists,True


In [10]:
# Compact profile for dashboard and analysis planning.
feature_profile = []
for feature in [
    "tenure_group", "age_group", "monthly_charge_band",
    "customer_value_segment", "referral_group",
    "contract_risk_group", "descriptive_risk_segment",
    "customer_engagement_profile",
]:
    summary = (
        feature_df.groupby(feature, observed=True)
        .agg(customers=("customer_id", "size"), churn_rate=("churn_flag", "mean"))
        .reset_index()
    )
    summary.insert(0, "feature", feature)
    feature_profile.append(summary.rename(columns={feature: "segment"}))

feature_profile = pd.concat(feature_profile, ignore_index=True)
feature_profile["churn_rate"] = feature_profile["churn_rate"].round(4)
feature_profile

,feature,segment,customers,churn_rate
0,tenure_group,1–6 months,1470,0.5333
1,tenure_group,7–12 months,716,0.3534
2,tenure_group,13–24 months,1024,0.2871
3,tenure_group,25–48 months,1594,0.2039
4,tenure_group,49–72 months,2239,0.0951
5,age_group,19–29,1401,0.2170
6,age_group,30–44,1943,0.2445
7,age_group,45–59,1917,0.2394
8,age_group,60–69,1004,0.3058
9,age_group,70+,778,0.4165


## Stage 5 Deliverable — Feature-Enhanced Dataset

The project now has `data/processed/telco_customer_churn_features.csv`, containing all 7,043 customers, the 52 prepared fields, and 12 documented business features for a total of 64 columns. The reusable feature pipeline preserves customer identity and source values, uses stable category rules, validates every engineered field, and distinguishes descriptive segmentation from predictive modeling.

---

**Developed and Designed by Emmanuel Onuoha**

# Stage 6 — Exploratory Data Analysis

This stage examines where churn is concentrated and what recorded characteristics distinguish churned customers. Every visual answers a stated business question and reports both rates and underlying customer volumes. The analysis is descriptive: associations identify where to investigate and intervene, but do not establish causation.

In [11]:
import plotly.express as px
import plotly.graph_objects as go
from plotly.subplots import make_subplots

from src.eda import (
    BLUE, ORANGE, RED, TEAL,
    churn_rate_bar,
    churn_reason_summary,
    churn_summary,
    city_churn_summary,
)

eda_df = pd.read_csv(
    FEATURE_DATA_PATH,
    dtype={"customer_id": "string", "zip_code": "string"},
)
OVERALL_CHURN_RATE = eda_df["churn_flag"].mean()
print(f"EDA population: {len(eda_df):,} customers")
print(f"Overall churn rate: {OVERALL_CHURN_RATE:.2%}")

EDA population: 7,043 customers
Overall churn rate: 26.54%


## 6.1 Portfolio Baseline

**Business question:** What is the scale of churn in the current customer snapshot?

The portfolio contains 7,043 customers: 1,869 churned, 4,720 stayed, and 454 joined. The overall churn rate is **26.54%**, meaning approximately one in four customer records is associated with churn. All subsequent segment rates should be compared with this portfolio baseline while also considering segment size.

In [12]:
status_summary = (
    eda_df.groupby("customer_status", observed=True)
    .agg(customers=("customer_id", "size"))
    .reset_index()
)
fig = px.bar(
    status_summary, x="customer_status", y="customers", text_auto=",",
    color="customer_status",
    color_discrete_map={"Stayed": TEAL, "Joined": BLUE, "Churned": RED},
    title="Customer Portfolio by Current Status",
)
fig.update_layout(template="plotly_white", showlegend=False, xaxis_title=None, yaxis_title="Customers")
fig.show()

## 6.2 Customer Demographics

**Business question:** Which demographic and household groups show the greatest churn exposure?

Gender is not a meaningful separator: female churn is 26.92% and male churn is 26.16%. Stronger differences appear elsewhere:

- Senior citizens churn at **41.68%**, compared with **23.61%** for non-seniors.
- Churn reaches **41.65%** among customers aged 70+, compared with **21.70%** among customers aged 19–29.
- Unmarried customers churn at **32.96%**, versus **19.66%** for married customers.
- Customers without dependents churn at **32.55%**, versus only **6.52%** for customers with dependents.

These groups may differ in tenure, contracts, services, and payment arrangements. Demographics should therefore guide experience design and monitoring—not serve as stand-alone explanations or exclusion rules.

In [13]:
demographic_specs = {
    "Age Group": ("age_group", ["19–29", "30–44", "45–59", "60–69", "70+"]),
    "Senior Citizen": ("senior_citizen", ["No", "Yes"]),
    "Married": ("married", ["No", "Yes"]),
    "Dependents": ("dependents", ["No", "Yes"]),
}
demographic_parts = []
for label, (column, order) in demographic_specs.items():
    part = churn_summary(eda_df, column, order).rename(columns={column: "segment"})
    part.insert(0, "dimension", label)
    demographic_parts.append(part)
demographic_summary = pd.concat(demographic_parts, ignore_index=True)
fig = px.bar(
    demographic_summary, x="segment", y="churn_rate", facet_col="dimension",
    facet_col_wrap=2, text="churn_rate_label", custom_data=["customers", "churned"],
    title="Churn Exposure Across Demographic and Household Groups",
)
fig.update_traces(marker_color=BLUE, textposition="outside")
fig.update_yaxes(tickformat=".0%", matches=None)
fig.update_xaxes(title=None)
fig.update_layout(template="plotly_white", height=650, showlegend=False)
fig.for_each_annotation(lambda annotation: annotation.update(text=annotation.text.split("=")[-1]))
fig.show()

## 6.3 Contract and Customer Lifecycle

**Business question:** At what contract commitment and relationship stage is churn most concentrated?

Contract type is one of the clearest churn separators. Month-to-month customers have a **45.84%** churn rate, compared with **10.71%** for one-year contracts and **2.55%** for two-year contracts. Month-to-month customers also account for 1,655 of the 1,869 churn events—**88.55% of all churn**.

Churn declines consistently with tenure: **53.33%** during months 1–6, **35.34%** during months 7–12, and **9.51%** during months 49–72. This identifies onboarding and the first contract year as the most important retention window. Contract and tenure overlap, so their effects will later be evaluated together rather than interpreted independently.

In [14]:
contract_summary = churn_summary(
    eda_df, "contract", ["Month-to-Month", "One Year", "Two Year"]
)
tenure_summary = churn_summary(
    eda_df, "tenure_group",
    ["1–6 months", "7–12 months", "13–24 months", "25–48 months", "49–72 months"],
)
display(contract_summary, tenure_summary)
churn_rate_bar(contract_summary, "contract", "Churn Rate by Contract Type").show()
churn_rate_bar(tenure_summary, "tenure_group", "Churn Rate by Customer Tenure").show()

,contract,customers,churned,churn_rate,churn_rate_label
0,Month-to-Month,3610,1655,0.458449,45.8%
1,One Year,1550,166,0.107097,10.7%
2,Two Year,1883,48,0.025491,2.5%


,tenure_group,customers,churned,churn_rate,churn_rate_label
0,1–6 months,1470,784,0.533333,53.3%
1,7–12 months,716,253,0.353352,35.3%
2,13–24 months,1024,294,0.287109,28.7%
3,25–48 months,1594,325,0.203890,20.4%
4,49–72 months,2239,213,0.095132,9.5%


## 6.4 Internet Service and Technology

**Business question:** Is churn concentrated in a particular internet-service group?

Customers with internet service churn at **31.83%**, compared with **7.41%** among customers without internet. Fiber optic is the most exposed internet type: 1,236 of 3,035 fiber customers churned, producing a **40.72%** rate. Cable is 25.66%, DSL is 18.58%, and customers without internet are 7.41%.

Fiber optic also tends to carry different charges, service bundles, and contract patterns. The result is an investigation priority—not proof that the technology itself causes departure. The company should examine fiber pricing, reliability, speed delivery, and competitor comparisons together.

In [15]:
internet_summary = churn_summary(
    eda_df, "internet_type", ["No Internet", "DSL", "Cable", "Fiber Optic"]
)
churn_rate_bar(
    internet_summary, "internet_type", "Churn Rate by Internet Type", color=ORANGE
).show()

## 6.5 Monthly Charges

**Business question:** How does churn vary with the customer's current monthly charge?

Churned customers average **$74.44** per month, compared with **$61.27** among non-churned customers. The relationship is not perfectly linear: churn is **10.86%** below $35, **23.65%** from $35–$69.99, **37.95%** from $70–$89.99, and **32.86%** at $90 or more.

The $70–$89.99 band has the highest rate, while the $90+ band still has substantial churn volume. Monthly charge partly reflects product mix, particularly internet type and bundled services. Price sensitivity should therefore be evaluated with contract and service configuration rather than through a blanket discount strategy.

In [16]:
charge_order = ["Under $35", "$35–$69.99", "$70–$89.99", "$90+"]
charge_summary = churn_summary(eda_df, "monthly_charge_band", charge_order)
fig = px.box(
    eda_df, x="churn_label", y="monthly_charge", color="churn_label",
    color_discrete_map={"No": TEAL, "Yes": RED}, points=False,
    title="Monthly-Charge Distribution by Churn Outcome",
)
fig.update_layout(template="plotly_white", showlegend=False, xaxis_title="Churned", yaxis_title="Monthly charge ($)")
fig.show()
churn_rate_bar(charge_summary, "monthly_charge_band", "Churn Rate by Monthly-Charge Band").show()

## 6.6 Payment Method

**Business question:** Which payment arrangements are associated with the greatest churn exposure?

Mailed check has the highest churn rate at **36.88%**, followed by bank withdrawal at **34.00%**. Credit card customers churn at **14.48%**. Bank withdrawal is the larger commercial concern because it combines elevated risk with 3,909 customers and 1,329 churn events.

Payment method may reflect contract tenure, customer preferences, and customer profile. The company should test whether payment-friction, failed-payment, or communication improvements help before treating payment method as causal.

In [17]:
payment_summary = churn_summary(
    eda_df, "payment_method", ["Credit Card", "Bank Withdrawal", "Mailed Check"]
)
churn_rate_bar(payment_summary, "payment_method", "Churn Rate by Payment Method").show()

## 6.7 Protection and Support Services

**Business question:** Are customers with protection and support services more likely to remain?

Online security and premium technical support show the largest differences:

- Online security: **14.61%** churn with the service versus **31.33%** without it.
- Premium technical support: **15.17%** versus **31.19%**.
- Online backup: **21.53%** versus **29.17%**.
- Device protection: **22.50%** versus **28.65%**.

Customers holding three or four protection/support services have churn rates of 12.43% and 5.32%, respectively. This may reflect stronger engagement, longer tenure, or more committed contracts as well as service value. Bundling and adoption should be tested through targeted campaigns rather than assumed to cause retention.

In [18]:
support_labels = {
    "online_security": "Online Security",
    "online_backup": "Online Backup",
    "device_protection_plan": "Device Protection",
    "premium_tech_support": "Premium Tech Support",
}
support_parts = []
for column, label in support_labels.items():
    part = churn_summary(eda_df, column, ["No", "Yes"]).rename(columns={column: "subscribed"})
    part.insert(0, "service", label)
    support_parts.append(part)
support_summary = pd.concat(support_parts, ignore_index=True)
fig = px.bar(
    support_summary, x="service", y="churn_rate", color="subscribed",
    barmode="group", text="churn_rate_label", custom_data=["customers", "churned"],
    color_discrete_map={"No": ORANGE, "Yes": TEAL},
    title="Churn Rate With and Without Protection and Support Services",
)
fig.update_yaxes(tickformat=".0%", title="Churn rate")
fig.update_xaxes(title=None)
fig.update_layout(template="plotly_white", legend_title="Subscribed")
fig.show()

## 6.8 Referrals and Advocacy

**Business question:** Does customer advocacy distinguish stronger relationships?

Customers with no referrals churn at **32.58%**. The 1–2 referral group is higher at **40.32%**, showing that a single referral does not automatically indicate loyalty. Churn then falls sharply to **9.40%** among customers with 3–5 referrals and **1.75%** among those with 6 or more.

Referral totals accumulate with relationship length, so long tenure likely contributes to this pattern. The business opportunity is to investigate whether sustained advocacy is an early signal of durable engagement and whether referral programs can be designed without confusing correlation with campaign impact.

In [19]:
referral_order = ["No Referrals", "1–2 Referrals", "3–5 Referrals", "6+ Referrals"]
referral_summary = churn_summary(eda_df, "referral_group", referral_order)
churn_rate_bar(referral_summary, "referral_group", "Churn Rate by Referral Activity", color=TEAL).show()

## 6.9 Satisfaction — Strong Signal, High Leakage Risk

**Business question:** How closely does recorded satisfaction align with churn, and can the field safely support prediction?

Every customer with satisfaction score 1 or 2 is recorded as churned, while no customer with score 4 or 5 churned. Score 3 has a 16.10% churn rate. This perfect separation at four score levels is unusually strong and suggests the score may have been collected or finalized after the churn decision, or may incorporate outcome knowledge.

Satisfaction is valuable for diagnosing customer experience, but it remains excluded from the baseline predictive model until collection timing is verified. Including it without provenance could produce impressive but operationally unusable model performance.

In [20]:
satisfaction_summary = churn_summary(eda_df, "satisfaction_score", [1, 2, 3, 4, 5])
churn_rate_bar(
    satisfaction_summary, "satisfaction_score",
    "Recorded Satisfaction and Churn: Diagnostic Use Only", color=RED,
).show()

## 6.10 Geographic Concentration

**Business question:** Are there service areas with unusually high churn that warrant operational investigation?

Among cities with at least 50 customers, San Diego is the clear outlier: **185 of 285 customers churned, or 64.91%**. The next-highest qualifying city, Escondido, is 31.37%. Los Angeles has 293 customers and a 26.62% rate, close to the portfolio baseline.

Several San Diego ZIP codes also show extremely high rates, but ZIP-level samples are small. Geographic rates must always display customer counts and a minimum-sample warning. The pattern warrants investigation of local network reliability, competitive pressure, service operations, or acquisition cohorts; location alone does not explain the outcome.

In [21]:
city_summary = city_churn_summary(eda_df, minimum_customers=50)
city_summary["churn_rate_label"] = city_summary["churn_rate"].map(lambda value: f"{value:.1%}")
fig = px.bar(
    city_summary.sort_values("churn_rate"), x="churn_rate", y="city", orientation="h",
    text="churn_rate_label", custom_data=["customers", "churned"],
    title="City Churn Rates — Minimum 50 Customers",
)
fig.update_traces(marker_color=ORANGE, textposition="outside")
fig.update_xaxes(tickformat=".0%", title="Churn rate")
fig.update_yaxes(title=None)
fig.update_layout(template="plotly_white", height=520)
fig.show()

## 6.11 Churn Categories and Reasons

**Business question:** What recorded reasons explain customer departures, and which are potentially actionable?

Competitor-related departures are the largest category: **841 customers, or 45.00% of all churn**. Attitude accounts for 16.80%, dissatisfaction 16.21%, price 11.29%, and other reasons 10.70%.

The largest specific reasons are competitor devices (313), competitor offers (311), support-person attitude (220), unknown reason (130), competitor data allowance (117), and competitor download speed (100). Competitor positioning and support experience therefore explain more churn than price alone.

These fields describe completed churn and are suitable for root-cause prioritization only. They cannot be used to identify future churners because the reason becomes available after departure.

In [22]:
category_summary, reason_summary = churn_reason_summary(eda_df)
top_reasons = reason_summary.head(10).sort_values("customers")
fig = make_subplots(
    rows=2, cols=1,
    row_heights=[0.42, 0.58],
    vertical_spacing=0.16,
    subplot_titles=["Share of Churn by Category", "Top 10 Recorded Reasons"],
)
fig.add_trace(
    go.Bar(x=category_summary["churn_category"], y=category_summary["share_of_churn"], marker_color=BLUE),
    row=1, col=1,
)
fig.add_trace(
    go.Bar(x=top_reasons["customers"], y=top_reasons["churn_reason"], orientation="h", marker_color=ORANGE),
    row=2, col=1,
)
fig.update_yaxes(tickformat=".0%", title="Share of churn", row=1, col=1)
fig.update_xaxes(title="Churned customers", row=2, col=1)
fig.update_yaxes(automargin=True, row=2, col=1)
fig.update_layout(
    template="plotly_white",
    height=850,
    showlegend=False,
    title="Why Customers Churned",
    margin=dict(l=220, r=40, t=90, b=70),
)
fig.show()

## 6.12 Revenue and Customer Lifetime Value

**Business question:** What customer value and revenue exposure is associated with churn?

Churned customers generated **$3.68 million** in accumulated historical revenue and represented **$139,130.85** in monthly-charge exposure in this snapshot. These amounts describe customers associated with churn; without churn dates they are not realized period losses.

Churned customers have lower mean accumulated revenue ($1,971.35 versus $3,418.37) and CLTV ($4,149.41 versus $4,490.92), largely alongside much shorter tenure (17.98 versus 37.59 months). However, 365 Premium Value customers and 425 High Value customers churned. Retention prioritization should therefore combine risk with value rather than treating all churn events as commercially equal.

Average revenue per tenure month is higher for churned customers ($98.33) than non-churned customers ($84.43), suggesting that churners can generate relatively high monthly economic exposure despite shorter relationships.

In [23]:
commercial_summary = (
    eda_df.groupby("churn_label", observed=True)
    .agg(
        customers=("customer_id", "size"),
        avg_monthly_charge=("monthly_charge", "mean"),
        avg_tenure=("tenure_in_months", "mean"),
        avg_total_revenue=("total_revenue", "mean"),
        avg_cltv=("cltv", "mean"),
        avg_revenue_per_month=("avg_revenue_per_tenure_month", "mean"),
    )
    .reset_index()
)
display(commercial_summary.round(2))
value_summary = churn_summary(
    eda_df, "customer_value_segment",
    ["Emerging Value", "Core Value", "High Value", "Premium Value"],
)
churn_rate_bar(value_summary, "customer_value_segment", "Churn Rate by Customer-Value Segment", color=TEAL).show()

,churn_label,customers,avg_monthly_charge,avg_tenure,avg_total_revenue,avg_cltv,avg_revenue_per_month
0,No,5174,61.27,37.59,3418.37,4490.92,84.43
1,Yes,1869,74.44,17.98,1971.35,4149.41,98.33


## 6.13 Exploratory Findings — Executive Interpretation

The clearest concentration of churn appears among customers in the early lifecycle, on month-to-month contracts, using fiber optic, lacking online security or premium support, and carrying moderate-to-high monthly charges. Older customers and customers without dependents also show elevated exposure. Competitor-related reasons dominate completed churn, while support attitude and service dissatisfaction indicate internal experience improvements alongside competitive response.

The analysis supports five immediate investigation priorities:

1. **Early-life retention:** examine onboarding and service experience during the first six months.
2. **Contract migration:** test value-based pathways from month-to-month to longer commitments.
3. **Fiber proposition:** investigate price, reliability, speed delivery, device offering, and competitor pressure together.
4. **Support experience:** improve support-person interactions and evaluate protection/support bundles.
5. **Geographic operations:** investigate the San Diego concentration using network and operational data not present in this file.

These priorities will be refined through multivariable segmentation, statistical validation, and predictive modeling.

## Stage 6 Deliverable — Structured Exploratory Analysis

The notebook now contains a question-led exploratory analysis covering customer demographics, contract and tenure, internet service, monthly charges, payment method, support services, referrals, satisfaction, geography, churn reasons, revenue, and customer value. Visuals use consistent definitions and show their underlying segment sizes. Written interpretations distinguish observed association, post-churn diagnosis, potential leakage, and causal uncertainty.

---

**Developed and Designed by Emmanuel Onuoha**

# Stage 7 — Customer Segmentation and Cohort Analysis

This stage moves beyond isolated attributes to examine combinations of lifecycle, contract, service, demographic, value, and geographic characteristics. The aim is to identify customer groups that are specific enough for targeted investigation and large enough to matter commercially.

## 7.1 Segmentation Principles

- `Joined` is a current status, not evidence of churn. Therefore, *new-customer risk* is evaluated through early tenure—especially months 1–6—rather than by assigning risk to all joined customers.
- Segment definitions use transparent conditions available in the feature-enhanced data.
- Segments intentionally overlap because one customer may require multiple interventions; totals must not be added together.
- Observed churn rate measures historical association within this snapshot and is not an individual probability.
- Active-customer counts show the currently reachable population within each segment.
- Satisfaction is analyzed separately because its timing indicates possible outcome leakage.
- Tenure groups are lifecycle cohorts, not true acquisition cohorts, because acquisition dates and calendar periods are unavailable.

In [24]:
from src.segmentation import (
    build_geographic_hotspots,
    build_segment_priority_table,
    build_tenure_contract_cohorts,
    build_tenure_internet_cohorts,
    export_segmentation_outputs,
)

segmentation_files = export_segmentation_outputs(FEATURE_DATA_PATH)
segment_priority = build_segment_priority_table(eda_df)
tenure_contract_cohorts = build_tenure_contract_cohorts(eda_df)
tenure_internet_cohorts = build_tenure_internet_cohorts(eda_df)
city_hotspots = build_geographic_hotspots(eda_df, "city", minimum_customers=50)
zip_hotspots = build_geographic_hotspots(eda_df, "zip_code", minimum_customers=20)

for output_name, output_path in segmentation_files.items():
    print(f"{output_name}: {output_path}")

prioritized_segments: D:\Data Analysis\Executive Portfolios\Customer Churn\Customer Churn\data\processed\prioritized_risk_segments.csv
tenure_contract_cohorts: D:\Data Analysis\Executive Portfolios\Customer Churn\Customer Churn\data\processed\tenure_contract_cohorts.csv
tenure_internet_cohorts: D:\Data Analysis\Executive Portfolios\Customer Churn\Customer Churn\data\processed\tenure_internet_cohorts.csv
city_hotspots: D:\Data Analysis\Executive Portfolios\Customer Churn\Customer Churn\data\processed\city_churn_hotspots.csv
zip_hotspots: D:\Data Analysis\Executive Portfolios\Customer Churn\Customer Churn\data\processed\zip_churn_hotspots.csv


## 7.2 Prioritization Method

Each actionable segment is assessed using:

1. **Observed churn rate:** churned customers divided by all customers in the segment.
2. **Active-customer reach:** currently non-churned customers matching the segment.
3. **Active monthly-charge exposure:** sum of current monthly charges among those active customers.
4. **Active CLTV:** sum of supplied CLTV among active customers in the segment.
5. **Opportunity index:** observed segment churn rate multiplied by active monthly-charge exposure.

The opportunity index is a transparent ranking heuristic balancing historical churn intensity and reachable monthly commercial exposure. It is not forecast loss, a calibrated probability, or expected campaign return. Because segments overlap, opportunity values are not additive.

In [25]:
priority_display = segment_priority.copy()
priority_display["observed_churn_rate"] = priority_display["observed_churn_rate"].map(lambda value: f"{value:.2%}")
for column in ["active_monthly_charge_exposure", "active_cltv", "opportunity_index"]:
    priority_display[column] = priority_display[column].map(lambda value: f"${value:,.2f}")
display(priority_display[[
    "priority_rank", "segment", "customers", "observed_churn_rate",
    "active_customers", "active_monthly_charge_exposure", "active_cltv",
    "recommended_focus",
]])

,priority_rank,segment,customers,observed_churn_rate,active_customers,active_monthly_charge_exposure,active_cltv,recommended_focus
0,1,Month-to-month without premium support,2985,48.54%,1536,"$85,088.05","$6,423,014.00",Proactive support trial and value-led contract migration
1,2,Fiber optic on month-to-month contract,1882,58.82%,775,"$67,889.60","$3,307,707.00",Fiber experience review and targeted commitment offer
2,3,High-value with high descriptive risk,1430,43.29%,811,"$61,900.75","$4,347,400.00",Priority human outreach with value-protection treatment
3,4,Early-tenure month-to-month,1367,57.06%,587,"$26,273.60","$2,377,690.00",First-six-month onboarding and service assurance
4,5,Early-tenure fiber month-to-month,839,73.30%,224,"$18,136.60","$896,267.00","Early fiber check-in, issue resolution, and plan review"
5,6,Senior with $90+ monthly charge,459,39.43%,278,"$28,261.15","$1,317,377.00",Accessible bill review and service-fit consultation
6,7,San Diego customers,285,64.91%,100,"$6,697.00","$446,003.00","Local network, service, acquisition, and competitor investigation"


## 7.3 Prioritized Actionable Segments

| Rank | Segment | Observed churn | Active customers | Active monthly exposure | Primary response |
|---:|---|---:|---:|---:|---|
| 1 | Month-to-month without premium support | 48.54% | 1,536 | $85,088.05 | Support trial and value-led contract migration |
| 2 | Fiber optic on month-to-month contract | 58.82% | 775 | $67,889.60 | Fiber experience review and commitment offer |
| 3 | High-value with high descriptive risk | 43.29% | 811 | $61,900.75 | Priority human outreach and value protection |
| 4 | Early-tenure month-to-month | 57.06% | 587 | $26,273.60 | First-six-month onboarding and service assurance |
| 5 | Early-tenure fiber month-to-month | 73.30% | 224 | $18,136.60 | Early fiber check-in and issue resolution |
| 6 | Senior with monthly charge of $90+ | 39.43% | 278 | $28,261.15 | Accessible bill and service-fit review |
| 7 | San Diego customers | 64.91% | 100 | $6,697.00 | Local network, acquisition, and competitor investigation |

Rank 1 has the largest reachable exposure, while Rank 5 has the highest focused churn intensity. These represent different intervention strategies: broad scalable treatment versus concentrated high-touch prevention.

In [26]:
fig = px.scatter(
    segment_priority,
    x="active_customers", y="observed_churn_rate",
    size="active_monthly_charge_exposure", color="opportunity_index",
    hover_name="segment", text="priority_rank",
    custom_data=["active_monthly_charge_exposure", "active_cltv", "recommended_focus"],
    color_continuous_scale="Blues", size_max=55,
    title="Risk Intensity vs Reach Across Actionable Segments",
)
fig.update_traces(textposition="top center")
fig.update_yaxes(tickformat=".0%", title="Observed churn rate")
fig.update_xaxes(title="Active customers in segment")
fig.update_layout(template="plotly_white", coloraxis_colorbar_title="Opportunity<br>index")
fig.show()

## 7.4 Contract–Tenure Lifecycle Cohorts

**Business question:** Does tenure reduce churn equally across contract types?

It does not. Month-to-month customers remain substantially exposed across the entire lifecycle: 57.06% churn during months 1–6, 44.69% during months 7–12, 40.52% during months 13–24, 36.92% during months 25–48, and 30.07% during months 49–72.

By contrast, two-year contract churn is zero in the first 24 months in this snapshot and remains below 3.3% in later cohorts. One-year churn ranges from 7.69% to 12.75%. Tenure alone therefore does not remove exposure for month-to-month customers; contract commitment remains important even among long-standing customers.

In [27]:
tenure_order = ["1–6 months", "7–12 months", "13–24 months", "25–48 months", "49–72 months"]
contract_order = ["Month-to-Month", "One Year", "Two Year"]
contract_matrix = (
    tenure_contract_cohorts.pivot(
        index="tenure_group", columns="contract", values="observed_churn_rate"
    ).reindex(index=tenure_order, columns=contract_order)
)
fig = px.imshow(
    contract_matrix, text_auto=".1%", aspect="auto",
    color_continuous_scale="OrRd", zmin=0, zmax=0.75,
    title="Observed Churn Rate by Tenure and Contract Cohort",
)
fig.update_xaxes(title="Contract")
fig.update_yaxes(title="Tenure cohort")
fig.update_layout(template="plotly_white", coloraxis_colorbar_tickformat=".0%")
fig.show()

## 7.5 Internet–Tenure Lifecycle Cohorts

**Business question:** Which internet customers are most exposed during the early lifecycle?

Fiber optic is the highest-risk internet group at every tenure level. Churn is **73.55%** for fiber customers in months 1–6 and **59.31%** in months 7–12, compared with 53.48% and 33.71% for cable and 48.35% and 21.89% for DSL. Even among customers in months 49–72, fiber churn remains 16.40%, versus 6.95% for cable and 4.47% for DSL.

This supports a dedicated early-life fiber journey, but additional analysis should distinguish service performance, charge levels, contract type, and acquisition source before selecting an intervention.

In [28]:
internet_order = ["No Internet", "DSL", "Cable", "Fiber Optic"]
internet_matrix = (
    tenure_internet_cohorts.pivot(
        index="tenure_group", columns="internet_type", values="observed_churn_rate"
    ).reindex(index=tenure_order, columns=internet_order)
)
fig = px.imshow(
    internet_matrix, text_auto=".1%", aspect="auto",
    color_continuous_scale="OrRd", zmin=0, zmax=0.75,
    title="Observed Churn Rate by Tenure and Internet Cohort",
)
fig.update_xaxes(title="Internet type")
fig.update_yaxes(title="Tenure cohort")
fig.update_layout(template="plotly_white", coloraxis_colorbar_tickformat=".0%")
fig.show()

## 7.6 Senior Customers With High Charges

The combined senior and $90+ charge segment contains 459 customers and has **39.43% churn**. Of these, 278 remain active and represent **$28,261.15 in monthly charges** and **$1.32 million in supplied CLTV**.

The appropriate response is not to make adverse decisions based on age. Instead, the segment supports accessible billing explanations, service-fit reviews, assisted support, and monitoring for affordability or complexity concerns. Any model using age-related fields will later require fairness review.

## 7.7 Low Satisfaction — Diagnostic Cohort Only

Scores 1 and 2 identify 1,440 customers, all of whom are recorded as churned. There are no active customers in this cohort, so it cannot support proactive targeting in the current snapshot.

This group should instead be used to diagnose what poor experiences preceded completed churn. Unless future data confirms that satisfaction is collected consistently before departure, it remains excluded from predictive and active-risk segmentation.

## 7.8 High-Value Customers at Descriptive Risk

The intersection of High/Premium Value and High/Very High descriptive risk contains 1,430 customers with **43.29% observed churn**. The 811 active customers represent **$61,900.75 in monthly charges** and **$4.35 million in supplied CLTV**.

This segment ranks third on the opportunity heuristic and is a strong candidate for high-touch outreach. However, the value segment inherits the source CLTV's unresolved provenance, while the risk segment is rule-based rather than predictive. It should guide exploratory prioritization until the independent model and financial assumptions are validated.

## 7.9 Geographic Hotspots

San Diego remains the leading city hotspot among locations with at least 50 customers: 185 of 285 customers churned (**64.91%**), leaving 100 active customers.

At ZIP-code level, six San Diego ZIP codes with at least 20 customers record churn between 85.00% and 91.67%: 92122, 92130, 92109, 92117, 92126, and 92121. Their sample sizes range from 20 to 36 customers, so they are investigation signals rather than stable forecasts.

The next business step should combine these hotspots with outage, network-performance, acquisition-channel, complaint, and competitor data. Without those sources, geography locates the issue but cannot explain it.

In [29]:
top_zip_hotspots = zip_hotspots.head(10).copy()
top_zip_hotspots["rate_label"] = top_zip_hotspots["observed_churn_rate"].map(lambda value: f"{value:.1%}")
fig = px.bar(
    top_zip_hotspots.sort_values("observed_churn_rate"),
    x="observed_churn_rate", y="zip_code", orientation="h",
    text="rate_label", custom_data=["customers", "churned_customers", "active_customers"],
    title="ZIP-Code Churn Hotspots — Minimum 20 Customers",
)
fig.update_traces(marker_color=ORANGE, textposition="outside")
fig.update_xaxes(tickformat=".0%", title="Observed churn rate")
fig.update_yaxes(title="ZIP code", type="category")
fig.update_layout(template="plotly_white")
fig.show()

## 7.10 Recommended Segment Actions

| Segment need | Suggested action | Initial measure |
|---|---|---|
| Broad month-to-month exposure without support | Offer time-limited premium support and a value-led contract option | Offer acceptance, support usage, and churn versus control |
| Fiber month-to-month | Conduct service-health check and present a targeted commitment benefit | Issue resolution, contract conversion, and churn versus control |
| High-value/high-risk | Prioritized human outreach with tailored service review | Contact rate, save rate, retained monthly charges, and net benefit |
| Early-tenure customers | Trigger onboarding contacts during the first six months | Early issue resolution and 90/180-day retention |
| Senior/high-charge | Provide accessible bill review and service-fit assistance | Resolution, plan-fit change, satisfaction, and retention |
| San Diego hotspot | Investigate operational and competitor drivers before mass offers | Reliability, complaints, root-cause resolution, and local churn |

All interventions should be evaluated with treatment and comparison groups where possible. Observed segment churn alone cannot establish campaign uplift.

In [30]:
segmentation_validation = pd.Series({
    "Seven actionable segments created": len(segment_priority) == 7,
    "All segments contain customers": segment_priority["customers"].gt(0).all(),
    "Churn rates valid": segment_priority["observed_churn_rate"].between(0, 1).all(),
    "Active counts valid": segment_priority["active_customers"].between(0, segment_priority["customers"]).all(),
    "Opportunity ranking complete": segment_priority["priority_rank"].tolist() == list(range(1, 8)),
    "Contract cohorts reconcile": tenure_contract_cohorts["customers"].sum() == len(eda_df),
    "Internet cohorts reconcile": tenure_internet_cohorts["customers"].sum() == len(eda_df),
    "San Diego hotspot reconciles": city_hotspots.iloc[0]["city"] == "San Diego",
    "All segmentation files exported": all(path.exists() for path in segmentation_files.values()),
})
display(segmentation_validation.to_frame("Passed"))
assert segmentation_validation.all(), "At least one segmentation check failed."

,Passed
Seven actionable segments created,True
All segments contain customers,True
Churn rates valid,True
Active counts valid,True
Opportunity ranking complete,True
Contract cohorts reconcile,True
Internet cohorts reconcile,True
San Diego hotspot reconciles,True
All segmentation files exported,True


## Stage 7 Deliverable — Prioritized Customer-Risk Segments

The project now has seven documented and ranked actionable segments, two lifecycle cohort datasets, and city- and ZIP-level hotspot tables. The priority framework balances observed churn intensity with active-customer reach and monthly commercial exposure, while preserving the distinction between overlapping descriptive segments and future model predictions.

---

**Developed and Designed by Emmanuel Onuoha**

# Stage 8 — Churn-Driver Assessment and Statistical Validation

This stage tests whether observed churn relationships are statistically distinguishable, measures their practical strength, and determines whether each field would genuinely be available before a customer leaves. Statistical association, predictive usefulness, operational availability, and causality are treated as separate questions.

## 8.1 Analytical Framework

A credible churn driver must pass more than a significance test:

1. **Temporal availability:** could the business know the value before churn?
2. **Outcome independence:** is the field distinct from the churn label or a model already trained on it?
3. **Association strength:** is the effect large enough to matter, not merely statistically significant in a large sample?
4. **Operational meaning:** can the business interpret and potentially act on the information?
5. **Redundancy control:** does the variable duplicate another feature or simply accumulate with tenure?
6. **Fairness:** could use of demographic information create inequitable treatment?
7. **Causal restraint:** does the evidence show association only, or support an intervention claim?

No variable in this observational snapshot is declared a proven causal driver. The term *potential driver* refers to a plausible pre-churn factor supported by descriptive and statistical evidence.

## 8.2 Statistical Methods

- **Categorical variables:** Pearson chi-square tests assess dependence with churn; bias-corrected Cramér's V measures effect strength.
- **Numerical variables:** two-sided Mann–Whitney U tests compare churned and non-churned distributions without assuming normality; rank-biserial correlation measures direction and effect size.
- **Multiple testing:** Benjamini–Hochberg false-discovery-rate correction is applied within each test family at 5%.
- **Effect interpretation:** Cramér's V below 0.10 is labelled negligible, 0.10–0.29 small, 0.30–0.49 moderate, and 0.50+ strong. Absolute rank-biserial correlation uses the same practical bands.
- **Assumption review:** categorical tests record expected cell counts; sparse results require caution.
- **Redundancy:** Spearman correlations of at least 0.70 are flagged for feature-selection review.

Threshold labels are practical conventions rather than universal laws. Sample size, business impact, and field availability remain part of interpretation.

In [31]:
from src.statistical_validation import (
    build_feature_governance,
    categorical_churn_associations,
    export_validation_outputs,
    numerical_churn_associations,
    numerical_redundancy_report,
)

categorical_associations = categorical_churn_associations(eda_df)
numerical_associations = numerical_churn_associations(eda_df)
feature_governance = build_feature_governance(eda_df)
numerical_redundancy = numerical_redundancy_report(eda_df)
validation_files = export_validation_outputs(FEATURE_DATA_PATH)

for output_name, output_path in validation_files.items():
    print(f"{output_name}: {output_path}")

categorical_associations: D:\Data Analysis\Executive Portfolios\Customer Churn\Customer Churn\data\processed\categorical_churn_associations.csv
numerical_associations: D:\Data Analysis\Executive Portfolios\Customer Churn\Customer Churn\data\processed\numerical_churn_associations.csv
numerical_redundancy: D:\Data Analysis\Executive Portfolios\Customer Churn\Customer Churn\data\processed\numerical_redundancy_report.csv
feature_governance: D:\Data Analysis\Executive Portfolios\Customer Churn\Customer Churn\data\processed\feature_governance.csv


## 8.3 Why Statistical Significance Is Not Enough

With 7,043 records, very small differences can produce low p-values. Device protection, streaming services, extra-data charges, and refunds are statistically associated with churn after correction but have negligible effect sizes. Conversely, gender, phone service, and average monthly long-distance charges are neither practically meaningful nor statistically significant after correction.

The project therefore ranks evidence by effect size, operational timing, and business relevance—not by p-value alone.

## 8.4 Categorical Association Results

After removing outcome-derived fields from interpretation, the strongest categorical associations are:

| Feature | Cramér's V | Strength | Interpretation |
|---|---:|---|---|
| Contract | 0.453 | Moderate | Strongest plausible categorical pre-churn factor |
| Internet type | 0.304 | Moderate | Technology/service proposition warrants multivariable review |
| Offer | 0.260 | Small | Offer groups differ, but assignment and timing may be confounded |
| Dependents | 0.248 | Small | Household context is associated but not directly actionable |
| Internet service | 0.227 | Small | Overlaps with internet type and should not be encoded redundantly |
| Payment method | 0.218 | Small | Useful operational signal requiring payment-friction investigation |
| Paperless billing | 0.191 | Small | Likely intertwined with payment and contract characteristics |
| Online security | 0.170 | Small | Potential retention-related service adoption signal |
| Unlimited data | 0.166 | Small | Plan configuration signal requiring price/service controls |
| Premium technical support | 0.164 | Small | Actionable support-adoption signal |

Contract and internet type are the only plausible categorical factors with moderate bivariate association. All listed results remain observational.

In [32]:
categorical_exclusions = {"customer_status", "churn_category", "churn_reason"}
candidate_categorical = (
    categorical_associations.loc[~categorical_associations["feature"].isin(categorical_exclusions)]
    .sort_values("cramers_v", ascending=True)
)
fig = px.bar(
    candidate_categorical, x="cramers_v", y="feature", orientation="h",
    color="effect_strength",
    category_orders={"effect_strength": ["Negligible", "Small", "Moderate", "Strong"]},
    color_discrete_map={"Negligible": "#C8D2DC", "Small": BLUE, "Moderate": ORANGE, "Strong": RED},
    hover_data=["adjusted_p_value", "assumption_flag"],
    title="Categorical Association With Churn — Outcome Fields Excluded",
)
fig.update_xaxes(title="Bias-corrected Cramér's V")
fig.update_yaxes(title=None)
fig.update_layout(template="plotly_white", height=700, legend_title="Effect strength")
fig.show()

## 8.5 Numerical Association Results

Among plausible pre-churn numerical fields, tenure has the strongest relationship: rank-biserial correlation is **−0.482**, a moderate effect, with churned customers having median tenure of 10 months versus 38 months for non-churned customers.

Accumulated total revenue (−0.345), total long-distance charges (−0.314), and total charges (−0.302) also have moderate effects. These are not automatically independent churn drivers: all accumulate with relationship length. Number of referrals (−0.278), monthly charge (+0.242), number of dependents (−0.237), age (+0.144), and average download usage (+0.144) have small effects.

The direction indicates comparison, not benefit or harm. For example, lower accumulated revenue among churners largely reflects shorter tenure, while higher current monthly charges may reflect fiber service and bundle composition.

In [33]:
numerical_exclusions = {"satisfaction_score", "churn_score", "cltv"}
candidate_numerical = (
    numerical_associations.loc[~numerical_associations["feature"].isin(numerical_exclusions)]
    .assign(absolute_effect=lambda frame: frame["rank_biserial"].abs())
    .sort_values("absolute_effect", ascending=True)
)
fig = px.bar(
    candidate_numerical, x="rank_biserial", y="feature", orientation="h",
    color="effect_strength",
    color_discrete_map={"Negligible": "#C8D2DC", "Small": BLUE, "Moderate": ORANGE, "Strong": RED},
    hover_data=["churned_median", "not_churned_median", "adjusted_p_value"],
    title="Numerical Association With Churn — Leakage and Provenance Risks Excluded",
)
fig.add_vline(x=0, line_color="#4D5966", line_width=1)
fig.update_xaxes(title="Rank-biserial correlation (direction relative to churn)")
fig.update_yaxes(title=None)
fig.update_layout(template="plotly_white", height=650, legend_title="Effect strength")
fig.show()

## 8.6 Leakage Demonstration

The strongest apparent relationships are precisely the fields that must not be used as predictors:

| Field | Effect | Why it is unsafe |
|---|---:|---|
| customer_status | Cramér's V = 1.000 | Directly identifies whether the customer churned |
| churn_category | Cramér's V = 1.000 | Populated only for churned customers |
| churn_reason | Cramér's V = 0.999 | Populated only after churn and includes sparse categories |
| satisfaction_score | Rank-biserial = −0.901 | Perfect separation at scores 1–2 and 4–5 suggests outcome timing |
| churn_score | Rank-biserial = +0.886 | Existing model output with unknown construction |

A model containing these fields could appear exceptionally accurate while failing at the real decision point. They remain useful for describing status, diagnosing completed churn, or benchmarking—not for predicting future churn.

## 8.7 Feature Redundancy and Confounding

Four numerical pairs exceed absolute Spearman correlation of 0.70:

| Pair | Spearman correlation | Interpretation |
|---|---:|---|
| Total charges and total revenue | 0.978 | Near-duplicate accumulated financial information |
| Tenure and total revenue | 0.913 | Revenue accumulation is strongly tied to relationship length |
| Tenure and total charges | 0.889 | Charges accumulate as tenure increases |
| Total long-distance charges and total revenue | 0.778 | Long-distance revenue contributes to total revenue |

The baseline model should not indiscriminately include every accumulated financial field. Candidate sets will compare a compact interpretable representation against broader alternatives, with transformations fitted on training data only.

In [34]:
display(numerical_redundancy[["feature_1", "feature_2", "spearman_correlation", "review_reason"]])

,feature_1,feature_2,spearman_correlation,review_reason
0,total_charges,total_revenue,0.978366,Potential redundancy or shared accumulation with tenure
1,tenure_in_months,total_revenue,0.912647,Potential redundancy or shared accumulation with tenure
2,tenure_in_months,total_charges,0.889476,Potential redundancy or shared accumulation with tenure
3,total_long_distance_charges,total_revenue,0.777501,Potential redundancy or shared accumulation with tenure


## 8.8 Potential Drivers vs Correlates

### Plausible, Actionable Pre-Churn Factors

- Contract type and tenure
- Internet type and service proposition
- Monthly charge in the context of service mix
- Premium technical support and online security adoption
- Payment method and possible payment friction
- Offer participation, subject to offer-assignment timing

These are suitable for multivariable modeling and intervention hypotheses, but not causal claims.

### Primarily Contextual or Confounded Correlates

- Accumulated charges and revenue, which strongly reflect tenure
- Demographics and household structure, which may identify experience differences but are not direct retention levers
- Referrals, which accumulate with tenure and may reflect existing loyalty
- Geography, which locates hotspots but may proxy for network, competition, or acquisition conditions
- Streaming and device features with negligible bivariate effects

### Outcome-Derived or Unverified Fields

- Customer status, churn category, churn reason, and churn score: exclude
- Satisfaction score: diagnostic only until timing is verified
- CLTV and its value segment: commercial prioritization only until provenance is verified

## 8.9 Feature-Governance Summary

Every one of the 64 fields has been assigned a governance status:

| Governance status | Fields | Modeling decision |
|---|---:|---|
| Eligible pre-churn candidate | 30 | Consider after preprocessing and collinearity review |
| Conditional — fairness review | 4 | Test separately and assess subgroup performance |
| Conditional — engineered aggregate | 2 | Compare with component-feature alternative |
| Conditional — provenance/timing unknown | 3 | Exclude from baseline |
| Descriptive — engineered reporting feature | 9 | Dashboard and segmentation use only |
| Descriptive — geography | 5 | Hotspot analysis; exclude from baseline |
| Excluded — constant, identifier, leakage, post-outcome, or external score | 9 | Do not use as predictive inputs |
| Target | 2 | `churn_label`/`churn_flag`; use one target representation |

The detailed field-level decision and rationale are exported to `data/processed/feature_governance.csv`.

In [35]:
governance_summary = (
    feature_governance.groupby("governance_status", observed=True)
    .agg(fields=("feature", "size"))
    .sort_values("fields", ascending=False)
)
display(governance_summary)
display(feature_governance)

,fields
governance_status,
Eligible pre-churn candidate,30
Descriptive — engineered reporting feature,9
Descriptive — geography,5
Conditional — fairness review,4
Exclude — constant,3
Conditional — engineered aggregate,2
Conditional — provenance unknown,2
Exclude — direct leakage,2
Exclude — post-outcome,2


,feature,governance_status,rationale
0,protection_support_service_count,Conditional — engineered aggregate,Potentially useful but duplicates component service indicators; compare in alternatives
1,service_count,Conditional — engineered aggregate,Potentially useful but duplicates component service indicators; compare in alternatives
2,age,Conditional — fairness review,Potentially sensitive demographic information requiring fairness assessment
3,gender,Conditional — fairness review,Potentially sensitive demographic information requiring fairness assessment
4,senior_citizen,Conditional — fairness review,Potentially sensitive demographic information requiring fairness assessment
...,...,...,...
59,customer_id,Exclude — identifier,Unique reference has no intended behavioral meaning
60,churn_category,Exclude — post-outcome,Recorded only to explain a completed churn event
61,churn_reason,Exclude — post-outcome,Recorded only to explain a completed churn event
62,churn_flag,Target,Defines or numerically restates the churn outcome


## 8.10 Statistical and Leakage Conclusions

Contract, internet type, and tenure have the strongest credible bivariate relationships with churn. Support/security adoption, payment method, monthly charges, offers, referrals, and household context add smaller signals that may become useful in combination. Accumulated financial measures require careful redundancy control because they largely track tenure.

No tested association proves that changing the feature will reduce churn. Intervention claims require controlled campaign or quasi-experimental evidence. The next predictive stage will use a leakage-safe baseline feature set, preprocessing inside cross-validation, out-of-sample evaluation, threshold analysis, and fairness diagnostics.

In [36]:
validation_checks = pd.Series({
    "All 64 fields governed": len(feature_governance) == len(eda_df.columns) == 64,
    "Contract effect is moderate": categorical_associations.set_index("feature").loc["contract", "effect_strength"] == "Moderate",
    "Tenure effect is moderate": numerical_associations.set_index("feature").loc["tenure_in_months", "effect_strength"] == "Moderate",
    "Gender not significant after FDR": not categorical_associations.set_index("feature").loc["gender", "significant_after_fdr"],
    "Leakage fields excluded": feature_governance.set_index("feature").loc[["customer_status", "churn_category", "churn_reason", "churn_score"], "governance_status"].str.startswith("Exclude").all(),
    "Satisfaction conditional": feature_governance.set_index("feature").loc["satisfaction_score", "governance_status"].startswith("Conditional"),
    "Redundancy pairs found": len(numerical_redundancy) == 4,
    "All validation files exported": all(path.exists() for path in validation_files.values()),
})
display(validation_checks.to_frame("Passed"))
assert validation_checks.all(), "At least one Stage 8 validation failed."

,Passed
All 64 fields governed,True
Contract effect is moderate,True
Tenure effect is moderate,True
Gender not significant after FDR,True
Leakage fields excluded,True
Satisfaction conditional,True
Redundancy pairs found,True
All validation files exported,True


## Stage 8 Deliverable — Churn-Driver and Leakage Report

The project now has corrected statistical association results, practical effect sizes, numerical redundancy checks, and a field-level governance decision covering all 64 analytical variables. Plausible pre-churn factors have been separated from simple correlates, sensitive attributes, derived reporting features, outcome leakage, post-churn information, and unverified source scores. This establishes a credible, leakage-safe foundation for predictive modeling.

---

**Developed and Designed by Emmanuel Onuoha**

# Stage 9 — Confidence Intervals and Validated Analytical Findings

Stage 8 established association strength, corrected significance, redundancy, and leakage governance. This stage completes statistical validation by quantifying uncertainty around the most important business comparisons and consolidating the claims that the available evidence supports. Predictive modeling is deliberately deferred until this evidence layer is complete.

## 9.1 Confidence-Interval Framework

- Individual churn-rate intervals use the Wilson score method.
- Differences between two independent churn proportions use Newcombe confidence intervals.
- Risk-ratio intervals use the adjusted log method.
- Numerical differences use 3,000 deterministic bootstrap resamples with a documented random seed.
- All intervals use a 95% confidence level.

These intervals describe uncertainty under a repeated-sampling interpretation. If this CSV represents a complete synthetic demonstration population rather than a sample from an operating customer process, the observed values are exact for this file and the intervals should be treated as sensitivity measures—not proof of external generalizability.

In [37]:
from src.analytical_validation import (
    build_numeric_confidence_intervals,
    build_segment_comparisons,
    build_validated_findings,
    export_analytical_validation,
    overall_churn_interval,
)

overall_interval = overall_churn_interval(eda_df)
validated_comparisons = build_segment_comparisons(eda_df)
numeric_confidence_intervals = build_numeric_confidence_intervals(eda_df)
validated_findings = build_validated_findings(
    eda_df, validated_comparisons, numeric_confidence_intervals
)
analytical_validation_files = export_analytical_validation(FEATURE_DATA_PATH)

for output_name, output_path in analytical_validation_files.items():
    print(f"{output_name}: {output_path}")

segment_comparisons: D:\Data Analysis\Executive Portfolios\Customer Churn\Customer Churn\data\processed\validated_segment_comparisons.csv
numeric_intervals: D:\Data Analysis\Executive Portfolios\Customer Churn\Customer Churn\data\processed\validated_numeric_differences.csv
validated_findings: D:\Data Analysis\Executive Portfolios\Customer Churn\Customer Churn\data\processed\validated_analytical_findings.csv


## 9.2 Overall Churn Estimate

The observed churn rate is **26.54%**, with a Wilson 95% confidence interval of **25.52% to 27.58%**. This precisely describes the file's churn level under the sampling assumptions, but it does not establish how churn changes over time because all records belong to one reported quarter.

In [38]:
overall_interval.to_frame("Value")

,Value
customers,7043
churned_customers,1869
churn_rate,0.26537
ci_lower,0.255188
ci_upper,0.275807
confidence_level,0.95
method,Wilson score interval


## 9.3 Validated Segment Comparisons

| Comparison | Rate difference | 95% CI | Risk ratio | 95% CI |
|---|---:|---:|---:|---:|
| Months 1–6 vs months 49–72 | +43.82 pp | +40.96 to +46.61 pp | 5.61× | 4.88–6.41× |
| Month-to-month vs two-year | +43.30 pp | +41.48 to +45.04 pp | 17.98× | 13.46–23.56× |
| San Diego vs other cities | +39.99 pp | +34.19 to +45.40 pp | 2.60× | 2.37–2.87× |
| No dependents vs dependents | +26.04 pp | +24.24 to +27.71 pp | 5.00× | 4.12–6.00× |
| Fiber optic vs DSL | +22.14 pp | +19.53 to +24.66 pp | 2.19× | 1.96–2.44× |
| Bank withdrawal vs credit card | +19.52 pp | +17.52 to +21.48 pp | 2.35× | 2.12–2.60× |
| Senior vs non-senior | +18.08 pp | +15.04 to +21.15 pp | 1.77× | 1.63–1.92× |
| No online security vs online security | +16.72 pp | +14.67 to +18.68 pp | 2.14× | 1.91–2.40× |
| No premium support vs premium support | +16.02 pp | +13.96 to +18.00 pp | 2.06× | 1.84–2.29× |

Every interval excludes zero difference, and every risk-ratio interval remains above one. These comparisons are statistically stable within the dataset assumptions. They remain unadjusted bivariate relationships and may reflect contract, tenure, service mix, price, geography, or customer-profile differences acting together.

In [39]:
comparison_plot = validated_comparisons.sort_values("risk_difference")
fig = go.Figure(
    go.Scatter(
        x=comparison_plot["risk_difference"],
        y=comparison_plot["comparison_id"],
        mode="markers",
        marker=dict(size=11, color=BLUE),
        error_x=dict(
            type="data",
            symmetric=False,
            array=comparison_plot["risk_difference_ci_upper"] - comparison_plot["risk_difference"],
            arrayminus=comparison_plot["risk_difference"] - comparison_plot["risk_difference_ci_lower"],
        ),
        customdata=np.column_stack([
            comparison_plot["exposed_group"], comparison_plot["reference_group"],
            comparison_plot["risk_ratio"], comparison_plot["risk_ratio_ci_lower"],
            comparison_plot["risk_ratio_ci_upper"],
        ]),
        hovertemplate=(
            "%{customdata[0]} vs %{customdata[1]}<br>Risk difference: %{x:.1%}"
            "<br>Risk ratio: %{customdata[2]:.2f} "
            "(%{customdata[3]:.2f}–%{customdata[4]:.2f})<extra></extra>"
        ),
    )
)
fig.add_vline(x=0, line_dash="dash", line_color="#4D5966")
fig.update_xaxes(tickformat=".0%", title="Churn-rate difference with 95% confidence interval")
fig.update_yaxes(title=None)
fig.update_layout(template="plotly_white", height=600, title="Validated Bivariate Churn Differences")
fig.show()

## 9.4 Validated Numerical Differences

Bootstrap intervals support four important distributional comparisons:

- Churned customers' average monthly charge is **$13.18 higher**, with a 95% interval of **$11.79 to $14.54**.
- Churned customers' median tenure is **28 months lower**, with a 95% interval of **26 to 30 months lower**.
- Churned customers' median accumulated revenue is **$1,685.78 lower**, with a 95% interval of **$1,549.12 to $1,836.48 lower**.
- Churned customers' median supplied CLTV is **$382 lower**, with a 95% interval of **$285 to $478 lower**.

The accumulated-revenue difference is strongly connected to shorter tenure. The CLTV result remains commercially descriptive because the source does not document its calculation timing.

In [40]:
numeric_confidence_intervals

,feature,statistic,difference_churned_minus_not_churned,ci_lower,ci_upper,confidence_level,bootstrap_iterations,interval_excludes_zero
0,monthly_charge,mean,13.176209,11.791086,14.540905,0.95,3000,True
1,tenure_in_months,median,-28.000000,-30.000000,-26.000000,0.95,3000,True
2,total_revenue,median,-1685.775000,-1836.477250,-1549.123625,0.95,3000,True
3,cltv,median,-382.000000,-478.000000,-285.000000,0.95,3000,True


## 9.5 Validated Analytical Findings

The combined evidence supports the following claims within the dataset:

1. Churn is materially concentrated in the first six months and among month-to-month customers.
2. Fiber-optic customers have substantially higher observed churn than DSL customers.
3. Customers without premium support or online security have approximately twice the observed churn risk of subscribers.
4. Bank-withdrawal customers have more than twice the observed churn risk of credit-card customers.
5. San Diego is a statistically distinct hotspot within this snapshot, not merely the result of a handful of records.
6. Senior customers and customers without dependents show meaningful churn differences, but these demographic relationships require fairness-sensitive interpretation.
7. Churned customers have higher current monthly charges but substantially shorter tenure and lower accumulated revenue.
8. Contract, internet type, and tenure remain the strongest credible bivariate factors after combining effect size, statistical evidence, timing, and leakage review.

The evidence supports prioritizing investigation and controlled retention tests. It does not support claiming that changing any single field will cause churn reduction.

In [41]:
display(validated_findings)

,finding,evidence,validation_status,interpretation_limit
0,Overall portfolio churn,26.54% (95% CI 25.52%–27.58%),Validated descriptive estimate,Snapshot estimate; not a time-series churn rate
1,Customers in months 1–6 have greater churn exposure than customers in months 49–72,Risk difference 43.82% (95% CI 40.96%–46.61%); risk ratio 5.61 (95% CI 4.88–6.41),Validated association,Bivariate observational comparison; not causal
2,Month-to-month customers have greater churn exposure than two-year customers,Risk difference 43.30% (95% CI 41.48%–45.04%); risk ratio 17.98 (95% CI 13.46–23.56),Validated association,Bivariate observational comparison; not causal
3,San Diego customers have greater churn exposure than customers elsewhere,Risk difference 39.99% (95% CI 34.19%–45.40%); risk ratio 2.60 (95% CI 2.37–2.87),Validated association,Bivariate observational comparison; not causal
4,Customers without dependents have greater churn exposure,Risk difference 26.04% (95% CI 24.24%–27.71%); risk ratio 5.00 (95% CI 4.12–6.00),Validated association,Bivariate observational comparison; not causal
5,Fiber-optic customers have greater churn exposure than DSL customers,Risk difference 22.14% (95% CI 19.53%–24.66%); risk ratio 2.19 (95% CI 1.96–2.44),Validated association,Bivariate observational comparison; not causal
6,Bank-withdrawal customers have greater churn exposure than credit-card customers,Risk difference 19.52% (95% CI 17.52%–21.48%); risk ratio 2.35 (95% CI 2.12–2.60),Validated association,Bivariate observational comparison; not causal
7,Senior customers have greater churn exposure than non-senior customers,Risk difference 18.08% (95% CI 15.04%–21.15%); risk ratio 1.77 (95% CI 1.63–1.92),Validated association,Bivariate observational comparison; not causal
8,Customers without online security have greater churn exposure,Risk difference 16.72% (95% CI 14.67%–18.68%); risk ratio 2.14 (95% CI 1.91–2.40),Validated association,Bivariate observational comparison; not causal
9,Customers without premium technical support have greater churn exposure,Risk difference 16.02% (95% CI 13.96%–18.00%); risk ratio 2.06 (95% CI 1.84–2.29),Validated association,Bivariate observational comparison; not causal


## 9.6 Evidence Boundaries

- Confidence intervals do not repair selection bias, missing operational variables, or uncertain source provenance.
- Bivariate intervals do not adjust for confounding between tenure, contract, internet type, charges, and service adoption.
- The San Diego interval quantifies the difference in this snapshot but cannot reveal whether network performance, competition, acquisition source, or another local factor is responsible.
- Demographic differences should prompt service-equity review, not adverse treatment.
- Statistical evidence is not equivalent to campaign uplift; retention actions require treatment/control evaluation.
- External validity remains limited to the represented California Q3 population until additional periods and markets are supplied.

In [42]:
stage_9_checks = pd.Series({
    "Overall interval contains observed rate": overall_interval["ci_lower"] < overall_interval["churn_rate"] < overall_interval["ci_upper"],
    "Nine segment comparisons validated": len(validated_comparisons) == 9 and validated_comparisons["validated_difference"].all(),
    "Four numerical intervals created": len(numeric_confidence_intervals) == 4,
    "All numerical intervals exclude zero": numeric_confidence_intervals["interval_excludes_zero"].all(),
    "Fourteen findings registered": len(validated_findings) == 14,
    "All analytical validation files exported": all(path.exists() for path in analytical_validation_files.values()),
})
display(stage_9_checks.to_frame("Passed"))
assert stage_9_checks.all(), "At least one Stage 9 validation failed."

,Passed
Overall interval contains observed rate,True
Nine segment comparisons validated,True
Four numerical intervals created,True
All numerical intervals exclude zero,True
Fourteen findings registered,True
All analytical validation files exported,True


## Stage 9 Deliverable — Validated Analytical Findings

The project now has confidence intervals for overall churn, nine priority group comparisons, and four key numerical differences, together with a 14-item evidence register. Important EDA claims are supported by effect sizes, corrected significance tests, and uncertainty ranges, while causal, temporal, provenance, fairness, and external-validity limitations remain explicit.

---

**Developed and Designed by Emmanuel Onuoha**

# Stage 10 — Predictive Modeling and Model Evaluation

This stage develops a reproducible churn-probability model using only plausibly available pre-churn operational information. A dummy baseline, logistic regression, decision tree, random forest, and gradient-boosting model are evaluated on identical stratified training folds. Model selection balances ranking performance with interpretability rather than selecting complexity automatically.

## 10.1 Modeling Objective

The modeling target is `churn_flag`, where 1 represents churn and 0 represents no churn. The model estimates the probability that a customer belongs to the churn class based on information assumed to be available before departure.

The objective is not to reproduce the supplied `ChurnScore`. It is to build an independent, auditable pipeline that can rank customers for retention review. Model probability represents statistical risk under the available data—not certainty that a customer will leave or evidence that a proposed intervention will work.

## 10.2 Leakage-Safe Feature Set

The baseline uses 24 operational predictors: eight numerical and sixteen categorical fields.

### Numerical

- Number of dependents and referrals
- Tenure
- Average monthly long-distance charge and download usage
- Current monthly charge
- Total refunds and extra-data charges

### Categorical

- Marital status and offer
- Phone, multiple lines, and internet type
- Security, backup, device protection, premium support, streaming, and unlimited-data services
- Contract, paperless billing, and payment method

Excluded fields include the target and status, churn reasons/categories, supplied ChurnScore, satisfaction, CLTV, identifiers, constant fields, geography, sensitive age/gender indicators, descriptive risk rules, and redundant accumulated revenue measures. Demographic fields remain available for later subgroup auditing but do not drive baseline predictions.

## 10.3 Reproducible Experimental Design

- **Holdout:** 20% of customers are reserved as an untouched test set.
- **Training:** 80% is used for model development.
- **Stratification:** both sets preserve the 26.54% churn prevalence.
- **Cross-validation:** five shuffled stratified folds with random seed 42.
- **Preprocessing:** median imputation and standardization for numerical fields; most-frequent imputation and one-hot encoding for categorical fields.
- **Leakage prevention:** all preprocessing is inside the scikit-learn pipeline and is refitted within every training fold.
- **Selection metric:** average precision, also called PR-AUC, because it focuses on identifying the minority churn class.
- **Selection rule:** choose the simplest model within 0.02 mean cross-validated PR-AUC of the best candidate.
- **Final test:** the selected pipeline is evaluated on the holdout set only after the selection rule is applied.

The split contains 5,634 training customers and 1,409 test customers. The test set contains 374 churners and 1,035 non-churners.

In [43]:
from sklearn.metrics import precision_recall_curve, roc_curve

from src.modeling import (
    CATEGORICAL_FEATURES,
    MODEL_FEATURES,
    NUMERIC_FEATURES,
    train_model_suite,
)

model_result = train_model_suite(FEATURE_DATA_PATH)
selected_model_name = model_result["selected_model_name"]
cv_model_results = model_result["cv_results"]
holdout_results = model_result["test_results"]
selected_importance = model_result["feature_importance"]

print(model_result["selection_rationale"])
print(f"Training customers: {model_result['train_size']:,}")
print(f"Test customers: {model_result['test_size']:,}")

Selected Logistic Regression using a predefined 0.02 practical-equivalence tolerance on cross-validated PR-AUC. Best mean PR-AUC was 0.7643 (Gradient Boosting); eligible cutoff was 0.7443.
Training customers: 5,634
Test customers: 1,409


## 10.4 Candidate Models

| Model | Role and configuration | Interpretability |
|---|---|---|
| Dummy baseline | Predicts the training-set class prior | Benchmark only |
| Logistic regression | Regularized linear log-odds model, 2,000 maximum iterations | High; coefficients are auditable |
| Decision tree | Maximum depth 6; at least 25 customers per leaf | High at tree level |
| Random forest | 400 trees, maximum depth 10, minimum leaf size 5 | Moderate; ensemble requires summary explanations |
| Gradient boosting | 180 shallow trees, learning rate 0.05, minimum leaf size 20 | Moderate to low without explanation tools |

These are controlled benchmark configurations rather than exhaustive hyperparameter searches. This reduces overfitting to cross-validation and keeps the portfolio workflow understandable.

## 10.5 Cross-Validation Results

| Model | ROC-AUC | PR-AUC | Recall | Precision | F1 |
|---|---:|---:|---:|---:|---:|
| Gradient Boosting | 0.899 | 0.764 | 0.621 | 0.726 | 0.670 |
| Random Forest | 0.897 | 0.764 | 0.621 | 0.729 | 0.670 |
| Logistic Regression | 0.894 | 0.752 | 0.657 | 0.708 | 0.681 |
| Decision Tree | 0.871 | 0.689 | 0.625 | 0.667 | 0.642 |
| Dummy Baseline | 0.500 | 0.265 | 0.000 | 0.000 | 0.000 |

Gradient boosting has the best mean PR-AUC at 0.764. Logistic regression is only 0.012 lower, remains within the declared 0.02 tolerance, has the highest mean F1 and recall among the three strongest models at the 0.50 threshold, and is considerably easier to audit. It is therefore selected.

In [44]:
cv_display = cv_model_results[[
    "model", "cv_roc_auc_mean", "cv_roc_auc_std",
    "cv_pr_auc_mean", "cv_pr_auc_std",
    "cv_precision_mean", "cv_recall_mean", "cv_f1_mean",
]].copy()
display(cv_display.round(4))
fig = px.scatter(
    cv_model_results, x="cv_recall_mean", y="cv_precision_mean",
    size="cv_pr_auc_mean", color="cv_pr_auc_mean", hover_name="model",
    color_continuous_scale="Blues", size_max=32,
    title="Cross-Validated Precision–Recall Tradeoff",
)
label_offsets = {
    "Gradient Boosting": (-58, 30),
    "Random Forest": (58, 30),
    "Logistic Regression": (68, -22),
    "Decision Tree": (-52, -28),
    "Dummy Baseline": (0, 28),
}
for row in cv_model_results.itertuples():
    xshift, yshift = label_offsets[row.model]
    fig.add_annotation(
        x=row.cv_recall_mean, y=row.cv_precision_mean, text=row.model,
        showarrow=True, arrowhead=0, arrowwidth=1, arrowcolor="#8FA3BF",
        ax=xshift, ay=-yshift, bgcolor="rgba(255,255,255,0.88)",
        borderpad=3, font=dict(size=11, color="#17345B"),
    )
fig.update_xaxes(title="Mean recall", tickformat=".0%")
fig.update_yaxes(title="Mean precision", tickformat=".0%")
fig.update_layout(
    template="plotly_white", height=540,
    margin=dict(l=70, r=145, t=90, b=70),
    coloraxis_colorbar=dict(title="PR-AUC", x=1.03),
)
fig.show()

,model,cv_roc_auc_mean,cv_roc_auc_std,cv_pr_auc_mean,cv_pr_auc_std,cv_precision_mean,cv_recall_mean,cv_f1_mean
0,Gradient Boosting,0.8995,0.0080,0.7643,0.0208,0.7264,0.6214,0.6697
1,Random Forest,0.8969,0.0061,0.7640,0.0127,0.7294,0.6207,0.6704
2,Logistic Regression,0.8942,0.0052,0.7518,0.0105,0.7078,0.6569,0.6811
3,Decision Tree,0.8713,0.0107,0.6895,0.0185,0.6665,0.6247,0.6424
4,Dummy Baseline,0.5000,0.0000,0.2654,0.0001,0.0000,0.0000,0.0000


## 10.6 Untouched Holdout Evaluation

At the default 0.50 threshold, selected logistic regression achieves:

| Metric | Test result | Business interpretation |
|---|---:|---|
| ROC-AUC | 0.898 | Strong ranking across churners and non-churners |
| PR-AUC | 0.745 | Substantially above the 0.265 churn prevalence baseline |
| Brier score | 0.112 | Lower probability error than dummy baseline's 0.195 |
| Accuracy | 83.39% | Useful but not sufficient under class imbalance |
| Balanced accuracy | 77.68% | Accounts for both outcome classes |
| Precision | 70.00% | Seven in ten flagged test customers actually churned |
| Recall | 65.51% | Approximately two-thirds of test churners were identified |
| F1 | 67.68% | Harmonic balance of precision and recall |

The selected model identifies 245 of 374 churners, misses 129, and incorrectly flags 105 non-churners. Threshold 0.50 is a technical default, not the final retention-policy threshold.

In [45]:
display(holdout_results.round(4))
selected_test = holdout_results.set_index("model").loc[selected_model_name]
confusion_values = np.array([
    [selected_test["true_negatives"], selected_test["false_positives"]],
    [selected_test["false_negatives"], selected_test["true_positives"]],
])
fig = px.imshow(
    confusion_values, text_auto=",.0f", color_continuous_scale="Blues",
    x=["Predicted No Churn", "Predicted Churn"],
    y=["Actual No Churn", "Actual Churn"],
    title="Selected Logistic Regression — Test Confusion Matrix at 0.50",
)
fig.update_layout(template="plotly_white", coloraxis_showscale=False)
fig.show()

,model,threshold,roc_auc,pr_auc,brier_score,accuracy,balanced_accuracy,precision,recall,f1,true_negatives,false_positives,false_negatives,true_positives
0,Gradient Boosting,0.5,0.9001,0.7491,0.1124,0.8318,0.7634,0.7108,0.6176,0.6609,941,94,143,231
1,Logistic Regression,0.5,0.8985,0.7451,0.1123,0.8339,0.7768,0.7000,0.6551,0.6768,930,105,129,245
2,Random Forest,0.5,0.8947,0.7399,0.1150,0.8332,0.7652,0.7138,0.6203,0.6638,942,93,142,232
3,Decision Tree,0.5,0.8776,0.6932,0.1210,0.8105,0.7737,0.6295,0.6952,0.6607,882,153,114,260
4,Dummy Baseline,0.5,0.5000,0.2654,0.1950,0.7346,0.5000,0.0000,0.0000,0.0000,1035,0,374,0


## 10.7 Probability Ranking Curves

ROC-AUC measures overall ranking, while PR-AUC emphasizes performance on churners. Because churn prevalence is 26.54%, a non-informative precision–recall baseline is approximately 0.265. The selected model's PR-AUC of 0.745 is about 2.8 times that baseline.

Curves summarize ranking across all thresholds. They do not select the operating point; that requires campaign capacity and the relative costs of missed churners and unnecessary outreach.

In [46]:
y_test_model = model_result["y_test"]
selected_probabilities = model_result["test_probabilities"]
fpr, tpr, _ = roc_curve(y_test_model, selected_probabilities)
precision_curve, recall_curve, _ = precision_recall_curve(y_test_model, selected_probabilities)
fig = make_subplots(rows=1, cols=2, subplot_titles=["ROC Curve", "Precision–Recall Curve"])
fig.add_trace(go.Scatter(x=fpr, y=tpr, mode="lines", line=dict(color=BLUE), name="Selected model"), row=1, col=1)
fig.add_trace(go.Scatter(x=[0, 1], y=[0, 1], mode="lines", line=dict(color="#9AA5B1", dash="dash"), name="Random"), row=1, col=1)
fig.add_trace(go.Scatter(x=recall_curve, y=precision_curve, mode="lines", line=dict(color=TEAL), name="Selected model"), row=1, col=2)
fig.add_hline(y=float(y_test_model.mean()), line_dash="dash", line_color="#9AA5B1", row=1, col=2)
fig.update_xaxes(title="False-positive rate", row=1, col=1)
fig.update_yaxes(title="True-positive rate", row=1, col=1)
fig.update_xaxes(title="Recall", row=1, col=2)
fig.update_yaxes(title="Precision", row=1, col=2)
fig.update_layout(template="plotly_white", height=480, showlegend=False, title="Selected Model Ranking Performance on Holdout Data")
fig.show()

## 10.8 Model Interpretation

The fitted logistic model contains 36 transformed coefficients after one-hot encoding. Larger positive coefficients increase modeled log-odds relative to their reference categories; negative coefficients reduce them. Numerical coefficients represent a one-standard-deviation increase because numerical preprocessing includes standardization.

Prominent terms include monthly charge, referrals, contract categories, tenure, premium support, online security, payment method, and household measures. These broadly align with EDA, but some conditional coefficient directions differ from bivariate results because correlated services, charges, and contract attributes are held constant simultaneously.

Coefficient magnitude is not causal importance. Categorical coefficients are reference-dependent, numeric and binary terms operate on different scales, and correlated predictors can redistribute effects. The next explanation stage should combine signed coefficients with grouped or permutation-based importance and individual prediction explanations.

In [47]:
top_coefficients = selected_importance.head(15).sort_values("signed_effect")
fig = px.bar(
    top_coefficients, x="signed_effect", y="feature", orientation="h",
    color="signed_effect", color_continuous_scale=[RED, "#F2F4F7", TEAL],
    color_continuous_midpoint=0,
    title="Largest Selected-Model Coefficients — Conditional Associations",
)
fig.add_vline(x=0, line_color="#4D5966", line_width=1)
fig.update_xaxes(title="Signed logistic coefficient")
fig.update_yaxes(title=None)
fig.update_layout(template="plotly_white", height=600, coloraxis_showscale=False)
fig.show()

## 10.9 Reproducibility Artifacts

The modeling pipeline exports:

- Serialized preprocessing and selected model pipeline
- Cross-validation results for every candidate
- Untouched holdout results
- Holdout customer probabilities and classifications
- Training/test split membership
- Selected-model coefficients or feature importance
- JSON metadata containing feature lists, exclusions, versions, split rules, seed, and selected metrics

Persisting split membership prevents later stages from accidentally redefining the holdout population. Saving the complete preprocessing pipeline ensures the Streamlit application will transform future customer inputs exactly as the model expects.

## 10.10 Current Model Limitations

- The model is validated on a random holdout from the same single-quarter California snapshot, not on a later time period or external market.
- Threshold 0.50 has not been optimized for campaign capacity or financial consequences.
- Probability calibration requires dedicated assessment before probabilities are presented as expected rates.
- Sensitive demographics are excluded from prediction, but subgroup performance still requires fairness evaluation.
- Offer assignment may be confounded with acquisition and lifecycle processes.
- Missing operational variables—complaints, outages, failed payments, contacts, and acquisition source—limit achievable explanation.
- Model performance does not demonstrate that retention treatment will change customer behavior.

In [48]:
stage_10_checks = pd.Series({
    "Twenty-four model predictors": len(MODEL_FEATURES) == 24,
    "Five candidate models compared": len(cv_model_results) == 5 and len(holdout_results) == 5,
    "Selected model is logistic regression": selected_model_name == "Logistic Regression",
    "Training and test rows reconcile": model_result["train_size"] + model_result["test_size"] == len(eda_df),
    "Holdout PR-AUC exceeds prevalence": selected_test["pr_auc"] > y_test_model.mean(),
    "Holdout ROC-AUC exceeds 0.85": selected_test["roc_auc"] > 0.85,
    "Prediction count reconciles": len(selected_probabilities) == model_result["test_size"],
    "All model artifacts exported": all(path.exists() for path in model_result["paths"].values()),
})
display(stage_10_checks.to_frame("Passed"))
assert stage_10_checks.all(), "At least one Stage 10 validation failed."

,Passed
Twenty-four model predictors,True
Five candidate models compared,True
Selected model is logistic regression,True
Training and test rows reconcile,True
Holdout PR-AUC exceeds prevalence,True
Holdout ROC-AUC exceeds 0.85,True
Prediction count reconciles,True
All model artifacts exported,True


## Stage 10 Deliverable — Reproducible Model-Development Pipeline

The project now has a leakage-safe, fully reproducible modeling pipeline comparing a dummy benchmark and four interpretable classification approaches. Logistic regression was selected using a declared simplicity tolerance on cross-validated PR-AUC and achieved strong holdout ranking with balanced precision and recall. The complete preprocessing pipeline, model, split membership, predictions, coefficients, metrics, and metadata are saved for threshold analysis, explanation, Streamlit integration, and reproducibility.

---

**Developed and Designed by Emmanuel Onuoha**

# Stage 11 — Threshold Selection, Calibration, Fairness, and Model Exploration

This stage converts model ranking performance into an operating decision. Threshold selection uses out-of-fold training probabilities, calibration is assessed on the untouched holdout population, and subgroup performance is audited using demographic fields that were excluded from prediction.

## 11.1 Why the Threshold Matters

ROC-AUC and PR-AUC evaluate probability ranking across all thresholds, but a retention team must eventually decide which customers to contact. A lower threshold flags more customers and captures more churners, but it also increases unnecessary interventions. A higher threshold concentrates resources and improves precision, but misses more customers who later churn.

Because missing a likely churner may be more costly than contacting an additional non-churner, the project establishes a minimum recall requirement of 80%. Among out-of-fold training thresholds meeting that condition, it selects the threshold with the highest precision. This rule is fixed before evaluating the holdout threshold result.

In [49]:
from src.model_evaluation import (
    MINIMUM_RECALL,
    run_model_evaluation,
)

evaluation_result = run_model_evaluation(
    feature_path=FEATURE_DATA_PATH,
    model_path=Path("artifacts/modeling/selected_churn_model.joblib"),
    split_path=Path("artifacts/modeling/split_membership.csv"),
)
selected_threshold = evaluation_result["selected_threshold"]
threshold_analysis = evaluation_result["threshold_table"]
threshold_holdout_metrics = evaluation_result["holdout_metrics"]
calibration_table = evaluation_result["calibration_table"]
calibration_metrics = evaluation_result["calibration_metrics"]
fairness_metrics = evaluation_result["fairness_metrics"]
fairness_gaps = evaluation_result["fairness_gaps"]

print(f"Selected operating threshold: {selected_threshold:.2f}")
print(evaluation_result["threshold_rationale"])

Selected operating threshold: 0.32
Selected the highest-precision out-of-fold threshold with recall at least 80%.


## 11.2 Threshold Selection on Out-of-Fold Training Predictions

The selected threshold is **0.32**. On out-of-fold training predictions it produces:

- Recall: **80.33%**
- Precision: **60.69%**
- F1: **69.14%**
- F2: **75.45%**
- Flagged population: **35.13%**

F2 is reported because it weights recall twice as heavily as precision, but it does not select the threshold by itself. The explicit operating rule is the highest precision while preserving at least 80% recall.

In [50]:
fig = go.Figure()
for metric, color in [("precision", BLUE), ("recall", RED), ("f1", TEAL), ("f2", ORANGE)]:
    fig.add_trace(go.Scatter(
        x=threshold_analysis["threshold"], y=threshold_analysis[metric],
        mode="lines", name=metric.upper(), line=dict(color=color),
    ))
fig.add_vline(x=selected_threshold, line_dash="dash", line_color="#172B4D", annotation_text="Selected 0.32")
fig.add_hline(y=MINIMUM_RECALL, line_dash="dot", line_color="#7A869A", annotation_text="80% recall requirement")
fig.update_xaxes(title="Classification threshold")
fig.update_yaxes(title="Metric value", tickformat=".0%", range=[0, 1])
fig.update_layout(template="plotly_white", title="Out-of-Fold Threshold Tradeoffs", legend_title=None)
fig.show()

## 11.3 Holdout Performance at the Selected Threshold

| Metric | Threshold 0.50 | Selected 0.32 | Change |
|---|---:|---:|---:|
| Precision | 70.00% | 61.58% | −8.42 pp |
| Recall | 65.51% | 83.16% | +17.65 pp |
| F1 | 67.68% | 70.76% | +3.08 pp |
| Balanced accuracy | 77.68% | 82.21% | +4.53 pp |
| Accuracy | 83.39% | 81.76% | −1.63 pp |
| True positives | 245 | 311 | +66 |
| False negatives | 129 | 63 | −66 |
| False positives | 105 | 194 | +89 |
| True negatives | 930 | 841 | −89 |

The selected threshold achieves the retention objective: it identifies 311 of 374 churners and reduces missed churners by 51.16%. The tradeoff is 89 additional non-churners flagged for intervention. Whether that tradeoff is economically favorable will be tested in the retention-scenario stage.

ROC-AUC remains 0.898 and PR-AUC remains 0.745 because threshold changes classifications, not probability ranking.

In [51]:
threshold_holdout_display = pd.Series(threshold_holdout_metrics, name="Value").to_frame()
display(threshold_holdout_display)
selected_confusion = np.array([
    [threshold_holdout_metrics["true_negatives"], threshold_holdout_metrics["false_positives"]],
    [threshold_holdout_metrics["false_negatives"], threshold_holdout_metrics["true_positives"]],
])
fig = px.imshow(
    selected_confusion, text_auto=",.0f", color_continuous_scale="Blues",
    x=["Predicted No Churn", "Predicted Churn"],
    y=["Actual No Churn", "Actual Churn"],
    title="Holdout Confusion Matrix at Selected Threshold 0.32",
)
fig.update_layout(template="plotly_white", coloraxis_showscale=False)
fig.show()

,Value
threshold,0.320000
roc_auc,0.898481
pr_auc,0.745057
brier_score,0.112348
accuracy,0.817601
balanced_accuracy,0.822056
precision,0.615842
recall,0.831551
f1,0.707622
true_negatives,841.000000


## 11.4 Probability Calibration

A well-calibrated model assigns probabilities that align with observed outcome frequencies. The holdout assessment produces:

- Brier score: **0.1123**
- Log loss: **0.3476**
- Expected calibration error: **2.07 percentage points**
- Calibration intercept: **−0.001**; ideal is 0
- Calibration slope: **1.063**; ideal is 1

These results indicate good overall calibration in the holdout snapshot. Calibration is not perfect in every probability band, and it may drift in future periods or markets. Probabilities should therefore be monitored and recalibrated when fresh labeled data becomes available.

In [52]:
fig = go.Figure()
fig.add_trace(go.Scatter(
    x=calibration_table["mean_predicted_probability"],
    y=calibration_table["observed_churn_rate"],
    mode="lines+markers", marker=dict(size=9, color=BLUE),
    line=dict(color=BLUE), name="Observed calibration",
))
fig.add_trace(go.Scatter(
    x=[0, 1], y=[0, 1], mode="lines",
    line=dict(color="#9AA5B1", dash="dash"), name="Perfect calibration",
))
fig.update_xaxes(title="Mean predicted churn probability", tickformat=".0%", range=[0, 1])
fig.update_yaxes(title="Observed churn rate", tickformat=".0%", range=[0, 1])
fig.update_layout(template="plotly_white", title="Holdout Calibration by Probability Decile")
fig.show()

## 11.5 Fairness and Subgroup Performance Audit

Gender, age, and senior status were excluded from the model inputs and are used only to audit outcomes. Excluding protected characteristics does not guarantee equal performance because operational variables may act as proxies and subgroup churn prevalence differs.

### Gender

Female recall is 86.21% and male recall is 79.53%, a **6.67-point gap**. False-positive rates are similar at 19.15% and 18.34%.

### Senior Status

Senior recall is 92.78% versus 79.78% for non-seniors, a **13.00-point gap**. Seniors also have much higher observed churn prevalence, which affects precision and selection rates.

### Age Groups

Recall ranges from **68.97% for ages 19–29** to **95.00% for ages 70+**, a **26.03-point gap**. The youngest group receives the lowest recall, while the oldest group has only 137 holdout customers. This gap requires monitoring, uncertainty-aware review, and investigation before automated use.

No single metric or universal cutoff proves fairness. The audit does not conclude that the model is discriminatory or fair; it identifies subgroup performance differences requiring governance.

In [53]:
display(fairness_metrics.round(4))
display(fairness_gaps.round(4))
fig = px.bar(
    fairness_metrics, x="group", y="recall", color="attribute",
    text=fairness_metrics["recall"].map(lambda value: f"{value:.1%}"),
    facet_col="attribute", facet_col_wrap=1,
    hover_data=["customers", "actual_churn_rate", "precision", "false_positive_rate"],
    title="Holdout Recall Across Demographic Audit Groups",
)
fig.add_hline(y=threshold_holdout_metrics["recall"], line_dash="dash", line_color="#4D5966")
fig.update_yaxes(tickformat=".0%", range=[0, 1], title="Recall")
fig.update_xaxes(title=None)
fig.update_layout(template="plotly_white", height=850, showlegend=False)
fig.for_each_annotation(lambda annotation: annotation.update(text=annotation.text.split("=")[-1]))
fig.show()

,attribute,group,customers,actual_churn_rate,selection_rate,precision,recall,false_positive_rate,true_negative_rate,balanced_accuracy,roc_auc,true_negatives,false_positives,false_negatives,true_positives
0,gender,Female,720,0.2819,0.3806,0.6387,0.8621,0.1915,0.8085,0.8353,0.8993,418,99,28,175
1,gender,Male,689,0.2482,0.3353,0.5887,0.7953,0.1834,0.8166,0.8060,0.8979,423,95,35,136
2,senior_citizen,No,1201,0.2306,0.3331,0.5525,0.7978,0.1937,0.8063,0.8021,0.8836,745,179,56,221
3,senior_citizen,Yes,208,0.4663,0.5048,0.8571,0.9278,0.1351,0.8649,0.8963,0.9420,96,15,7,90
4,age_group,19–29,274,0.2117,0.2883,0.5063,0.6897,0.1806,0.8194,0.7545,0.8586,177,39,18,40
5,age_group,30–44,391,0.2379,0.3606,0.5532,0.8387,0.2114,0.7886,0.8137,0.8846,235,63,15,78
6,age_group,45–59,391,0.2353,0.3350,0.5878,0.8370,0.1806,0.8194,0.8282,0.8984,245,54,15,77
7,age_group,60–69,216,0.3287,0.4074,0.6705,0.8310,0.2000,0.8000,0.8155,0.8864,116,29,12,59
8,age_group,70+,137,0.4380,0.4818,0.8636,0.9500,0.1169,0.8831,0.9166,0.9649,68,9,3,57


,attribute,groups,recall_gap,false_positive_rate_gap,selection_rate_gap,minimum_group_size
0,age_group,5,0.2603,0.0945,0.1934,137
1,gender,2,0.0667,0.0081,0.0453,689
2,senior_citizen,2,0.1300,0.0586,0.1718,208


## 11.6 High-Risk Customer KPI

After locking the model and threshold, the logistic pipeline is refitted on all labeled records for portfolio scoring. Among 5,174 active customers:

- **947 customers** meet or exceed the 0.32 high-risk threshold.
- They represent **18.30% of active customers**.
- Their current monthly-charge exposure is **$68,729.50**.
- Their supplied CLTV totals **$3,931,619**.

This completes the Stage 3 high-risk KPI definition. Because the final model is refitted on the full historical snapshot, these scores are intended for current portfolio prioritization and application demonstration; future operational reporting should use genuinely unseen, later-period customers.

In [54]:
portfolio_report = pd.Series({
    "Active customers": evaluation_result["report"]["active_customers"],
    "Active high-risk customers": evaluation_result["report"]["active_high_risk_customers"],
    "Active high-risk rate": evaluation_result["report"]["active_high_risk_rate"],
    "High-risk monthly-charge exposure": evaluation_result["report"]["active_high_risk_monthly_charge_exposure"],
    "High-risk CLTV": evaluation_result["report"]["active_high_risk_cltv"],
})
portfolio_report.to_frame("Value")

,Value
Active customers,5.174000e+03
Active high-risk customers,9.470000e+02
Active high-risk rate,1.830305e-01
High-risk monthly-charge exposure,6.872950e+04
High-risk CLTV,3.931619e+06


## 11.7 Deployment and Monitoring Rules

- Store threshold 0.32 separately from the model so policy can be reviewed without retraining.
- Display probability and risk classification together; never present a binary label without context.
- Do not trigger automatic adverse action. Scores support retention outreach only.
- Track contact volume, precision, recall where labels become available, calibration, subgroup performance, and score drift.
- Reassess the threshold when campaign capacity, contact cost, save rate, or customer value assumptions change.
- Recalibrate or retrain when later-period performance degrades.
- Keep sensitive demographic fields outside prediction and available only for authorized fairness monitoring.
- Treat the current portfolio high-risk count as a snapshot, not a permanent business constant.

In [55]:
stage_11_checks = pd.Series({
    "Threshold selected from out-of-fold training data": selected_threshold == 0.32,
    "Holdout recall exceeds requirement": threshold_holdout_metrics["recall"] >= MINIMUM_RECALL,
    "Holdout PR-AUC remains strong": threshold_holdout_metrics["pr_auc"] > 0.70,
    "Calibration error below five points": calibration_metrics["expected_calibration_error"] < 0.05,
    "Fairness audit covers three attributes": set(fairness_metrics["attribute"]) == {"gender", "senior_citizen", "age_group"},
    "Active high-risk KPI populated": evaluation_result["report"]["active_high_risk_customers"] == 947,
    "Portfolio scores cover all customers": len(evaluation_result["portfolio_scores"]) == len(eda_df),
    "All evaluation artifacts exported": all(path.exists() for path in evaluation_result["paths"].values()),
})
display(stage_11_checks.to_frame("Passed"))
assert stage_11_checks.all(), "At least one Stage 11 validation failed."

,Passed
Threshold selected from out-of-fold training data,True
Holdout recall exceeds requirement,True
Holdout PR-AUC remains strong,True
Calibration error below five points,True
Fairness audit covers three attributes,True
Active high-risk KPI populated,True
Portfolio scores cover all customers,True
All evaluation artifacts exported,True


## Stage 11 Deliverable — Model-Comparison and Threshold-Selection Report

The selected logistic model now has an out-of-fold operating threshold of 0.32, complete holdout classification metrics, threshold tradeoff analysis, calibration diagnostics, demographic subgroup auditing, a production-refitted pipeline, and portfolio risk scores. The threshold captures 83.16% of holdout churners with 61.58% precision, probabilities are well calibrated overall, and identified subgroup gaps are documented for monitoring. The current high-risk KPI is 947 active customers.

---

**Developed and Designed by Emmanuel Onuoha**

# Stage 12 — Model Explanation

This stage explains what the selected logistic model has learned globally and why it assigns a particular probability to an individual customer. Model behavior is explained separately from business causality: a feature can influence a prediction without proving that changing the feature will change churn.

## 12.1 Explanation Strategy

The explanation framework uses four complementary views:

1. **Holdout permutation importance:** measures the average loss in PR-AUC when one original input is shuffled. This shows which inputs the fitted model relies on for ranking unseen customers.
2. **Logistic coefficients:** show conditional direction and odds multipliers after preprocessing, relative to reference categories and other included fields.
3. **Marginal prediction profiles:** vary one field across the holdout background while keeping all others unchanged, then average the resulting probabilities.
4. **Exact local decomposition:** separates each customer's log-odds from a mean-transformed portfolio reference into additive feature contributions.

The SHAP package is not installed in the project environment. For logistic regression, exact coefficient-based additive decomposition provides a transparent local explanation without an approximation or additional dependency.

In [56]:
from src.model_explanation import run_model_explanation

explanation_result = run_model_explanation(
    feature_path=FEATURE_DATA_PATH,
    selected_model_path=Path("artifacts/modeling/selected_churn_model.joblib"),
    production_model_path=Path("artifacts/evaluation/production_churn_model.joblib"),
    split_path=Path("artifacts/modeling/split_membership.csv"),
)
coefficient_explanations = explanation_result["coefficient_table"]
permutation_explanations = explanation_result["permutation_importance"]
marginal_profiles = explanation_result["marginal_profiles"]
example_customer_id = explanation_result["example_customer_id"]
example_explanation = explanation_result["example_explanation"]

print(f"Reference probability: {explanation_result['base_probability']:.2%}")
print(f"Example active customer: {example_customer_id}")

Reference probability: 10.02%
Example active customer: 4927-WWOOZ


## 12.2 What Generally Drives the Model?

Holdout permutation importance is the primary global ranking because it evaluates the complete pipeline on unseen customers and returns importance at the original feature level.

| Rank | Feature | Mean PR-AUC loss when shuffled | Interpretation |
|---:|---|---:|---|
| 1 | Monthly charge | 0.298 | Largest contribution to unseen-customer ranking |
| 2 | Number of referrals | 0.145 | Strong engagement/lifecycle signal |
| 3 | Contract | 0.129 | Important commitment signal |
| 4 | Married | 0.093 | Conditional household signal; not a direct intervention lever |
| 5 | Tenure | 0.080 | Important lifecycle signal |
| 6 | Internet type | 0.045 | Service-proposition signal interacting with price and services |
| 7 | Phone service | 0.034 | Conditional service-configuration signal |
| 8 | Number of dependents | 0.033 | Household-context signal |
| 9 | Premium technical support | 0.022 | Actionable support-adoption signal |
| 10 | Payment method | 0.019 | Billing and payment-friction signal |
| 11 | Online security | 0.018 | Actionable service-adoption signal |

Every one of the top eleven features reduced PR-AUC in all 20 shuffle repetitions. Importance measures reliance, not direction and not causal impact. Correlated features can share or transfer importance.

In [57]:
top_permutation = permutation_explanations.head(15).sort_values("pr_auc_importance_mean")
fig = go.Figure(go.Bar(
    x=top_permutation["pr_auc_importance_mean"],
    y=top_permutation["feature"],
    orientation="h",
    marker_color=BLUE,
    error_x=dict(type="data", array=top_permutation["pr_auc_importance_std"]),
))
fig.update_xaxes(title="Mean holdout PR-AUC reduction after shuffling")
fig.update_yaxes(title=None)
fig.update_layout(template="plotly_white", height=620, title="Global Model Reliance — Holdout Permutation Importance")
fig.show()

## 12.3 Logistic Effects and Conditional Direction

A positive coefficient increases modeled churn log-odds relative to the field's reference or standardized baseline; a negative coefficient reduces them. Exponentiating a coefficient gives a conditional odds multiplier.

For numerical variables, the multiplier represents one training-standard-deviation increase. For categorical terms, it represents the listed category relative to the encoder's omitted reference. The model contains 36 transformed terms from 24 original inputs.

Coefficients must be interpreted conditionally. For example, bivariate EDA shows fiber optic has high churn, while the model's fiber coefficient can turn negative after holding monthly charge, contract, support, streaming, and other correlated service fields constant. This is statistical suppression, not evidence that fiber service prevents churn. Similar reversals can occur for marital status or phone configuration. Business recommendations should therefore combine EDA, validated associations, and model explanations rather than reading one coefficient causally.

In [58]:
largest_coefficients = coefficient_explanations.head(18).sort_values("coefficient")
fig = px.bar(
    largest_coefficients, x="coefficient", y="term", orientation="h",
    color="coefficient", color_continuous_scale=[TEAL, "#F2F4F7", RED],
    color_continuous_midpoint=0,
    hover_data=["original_feature", "conditional_odds_multiplier", "interpretation_unit"],
    title="Largest Production Logistic Coefficients",
)
fig.add_vline(x=0, line_color="#4D5966", line_width=1)
fig.update_xaxes(title="Conditional log-odds coefficient")
fig.update_yaxes(title=None)
fig.update_layout(template="plotly_white", height=680, coloraxis_showscale=False)
fig.show()

## 12.4 Partial and Marginal Relationships

The model's average prediction responds consistently to three key numerical inputs when other recorded values are held fixed:

- Moving tenure from 1 to 71 months lowers mean predicted churn from approximately **35.11% to 12.89%**.
- Moving monthly charge from about $19.70 to $107.38 raises mean predicted churn from approximately **4.44% to 61.98%**.
- Moving referrals from 0 to 9 lowers mean predicted churn from approximately **34.04% to 1.38%**.

For contract, the average modeled probability is approximately 33.29% under month-to-month, 17.11% under one-year, and 7.39% under two-year replacement scenarios. Premium support and online security also lower average modeled risk in their respective replacement profiles.

These profiles describe model response under artificial one-variable substitutions. Some combinations may be uncommon or unrealistic, and the profiles do not estimate causal treatment effects.

In [59]:
numeric_profiles = marginal_profiles.loc[marginal_profiles["feature_type"].eq("numeric")]
fig = px.line(
    numeric_profiles, x="numeric_value", y="mean_predicted_probability",
    facet_col="feature", facet_col_wrap=3, markers=True,
    title="Average Model Response to Key Numerical Inputs",
)
fig.update_yaxes(tickformat=".0%", title="Mean predicted probability")
fig.update_xaxes(matches=None)
fig.update_layout(template="plotly_white", height=450)
fig.for_each_annotation(lambda annotation: annotation.update(text=annotation.text.split("=")[-1]))
fig.show()

## 12.5 How an Individual Prediction Is Explained

The production model's transformed feature means define a reference log-odds value. Its sigmoid is **10.02%**; this is the probability at the mean transformed feature vector, not the arithmetic average customer probability.

For each customer:

1. Every transformed value is centered against the portfolio background mean.
2. The centered value is multiplied by its logistic coefficient.
3. One-hot terms are grouped back to their original business feature.
4. Positive contributions raise risk relative to the reference; negative contributions lower it.
5. The reference log-odds plus all grouped contributions exactly reconstruct the customer's probability.

This explains why the model produced a score. It does not say that changing the largest contribution will necessarily change the customer's behavior.

## 12.6 Example High-Risk Active Customer

Customer `4927-WWOOZ` is a newly joined, active customer with a **95.56% modeled churn probability**. The customer has two months of tenure, a month-to-month contract, a $91.45 monthly charge, no referrals, no online security, and no premium technical support.

The strongest risk-raising contributions are:

- Monthly charge: +1.852 log-odds
- Number of referrals: +0.998
- Contract: +0.926
- Tenure: +0.844
- Conditional marital-status contribution: +0.808

The model also identifies protective conditional contributions from internet type, streaming TV, device protection, phone service, and unlimited-data configuration. These protective terms do not cancel the dominant early-tenure, charge, referral, and contract signals.

The customer has not actually churned. The prediction should trigger a retention review or supportive outreach—not a claim that churn is certain.

In [60]:
display(example_explanation)
example_plot = example_explanation.sort_values("log_odds_contribution")
fig = px.bar(
    example_plot, x="log_odds_contribution", y="feature", orientation="h",
    color="effect",
    color_discrete_map={
        "Raises risk relative to portfolio background": RED,
        "Lowers risk relative to portfolio background": TEAL,
    },
    title=f"Why Customer {example_customer_id} Is Scored High Risk",
)
fig.add_vline(x=0, line_color="#4D5966", line_width=1)
fig.update_xaxes(title="Contribution to modeled log-odds")
fig.update_yaxes(title=None)
fig.update_layout(template="plotly_white", height=570, legend_title=None)
fig.show()

,feature,log_odds_contribution,effect,odds_multiplier_for_contribution,customer_id,predicted_probability,background_probability,absolute_contribution
0,monthly_charge,1.851665,Raises risk relative to portfolio background,6.370420,4927-WWOOZ,0.9556,0.100202,1.851665
1,number_of_referrals,0.997606,Raises risk relative to portfolio background,2.711782,4927-WWOOZ,0.9556,0.100202,0.997606
2,contract,0.926004,Raises risk relative to portfolio background,2.524400,4927-WWOOZ,0.9556,0.100202,0.926004
3,tenure_in_months,0.844305,Raises risk relative to portfolio background,2.326360,4927-WWOOZ,0.9556,0.100202,0.844305
4,married,0.808376,Raises risk relative to portfolio background,2.244261,4927-WWOOZ,0.9556,0.100202,0.808376
5,internet_type,-0.759909,Lowers risk relative to portfolio background,0.467709,4927-WWOOZ,0.9556,0.100202,0.759909
6,number_of_dependents,0.282692,Raises risk relative to portfolio background,1.326697,4927-WWOOZ,0.9556,0.100202,0.282692
7,streaming_tv,-0.212732,Lowers risk relative to portfolio background,0.808373,4927-WWOOZ,0.9556,0.100202,0.212732
8,device_protection_plan,-0.174207,Lowers risk relative to portfolio background,0.840123,4927-WWOOZ,0.9556,0.100202,0.174207
9,phone_service,-0.168239,Lowers risk relative to portfolio background,0.845152,4927-WWOOZ,0.9556,0.100202,0.168239


## 12.7 Portfolio Explanation Capability

Compact explanations have been generated for all **5,174 active customers**, retaining the three strongest positive and three strongest protective business-feature contributions where available. The exported file supports the future Streamlit customer lookup page.

A responsible interface should display:

- Predicted probability and the 0.32 operating threshold
- Risk classification and current customer status
- Strongest risk-raising and protective model contributions
- Plain-language explanation of each factor
- A warning that explanations describe model behavior, not causality
- A reminder that scores support retention assistance, not adverse action

## 12.8 Explanation Limitations

- Permutation importance can distribute importance unpredictably among correlated inputs.
- Coefficients are conditional on every other included variable and can reverse bivariate directions.
- One-hot coefficients depend on the omitted reference category.
- Marginal profiles may create unrealistic combinations when one field is changed in isolation.
- Local contribution size explains the model's calculation, not the feasibility or effect of changing that feature.
- The explanation background uses the current full snapshot and should be versioned when the population changes.
- Explanations inherit the model's data limitations, calibration limits, and subgroup performance gaps.

In [61]:
stage_12_checks = pd.Series({
    "Twenty-four global features ranked": len(permutation_explanations) == 24,
    "Thirty-six transformed coefficients documented": len(coefficient_explanations) == 36,
    "Permutation importance uses holdout data": permutation_explanations["repeats"].eq(20).all(),
    "Marginal profiles complete": set(marginal_profiles["feature"]) == {"tenure_in_months", "monthly_charge", "number_of_referrals", "contract", "internet_type", "premium_tech_support", "online_security", "payment_method"},
    "All active customers explained": explanation_result["metadata"]["active_customers_explained"] == 5_174,
    "Example is active customer": example_customer_id == "4927-WWOOZ",
    "Exact local reconstruction validated": len(explanation_result["grouped_contributions"]) == len(eda_df),
    "All explanation artifacts exported": all(path.exists() for path in explanation_result["paths"].values()),
})
display(stage_12_checks.to_frame("Passed"))
assert stage_12_checks.all(), "At least one Stage 12 validation failed."

,Passed
Twenty-four global features ranked,True
Thirty-six transformed coefficients documented,True
Permutation importance uses holdout data,True
Marginal profiles complete,True
All active customers explained,True
Example is active customer,True
Exact local reconstruction validated,True
All explanation artifacts exported,True


## Stage 12 Deliverable — Explainable Churn-Risk Model

The model now answers both required questions. Global holdout permutation importance and signed logistic effects show which fields drive ranking and in what conditional direction. Marginal profiles show how average predictions respond to important features, while exact mean-centered log-odds decomposition explains every active customer's score. All 5,174 active customers have exportable explanations, and model-behavior statements remain clearly separated from causal business claims.

---

**Developed and Designed by Emmanuel Onuoha**

# Stage 13 — Retention Strategy and Business-Impact Simulation

This stage connects model risk, customer value, intervention design, campaign cost, and assumed retention impact. Results are transparent scenarios rather than claimed savings. The simulator is reusable by the future Streamlit application so decision-makers can change assumptions instead of accepting one fixed forecast.

## 13.1 Eligible Campaign Population

The campaign population contains the **947 active customers** at or above the validated 0.32 model threshold. Together they represent:

- **18.30% of active customers**
- **$68,729.50 in total monthly charges**
- **$3,931,619 in supplied CLTV**
- **502.25 model-weighted expected churners**, calculated as the sum of predicted probabilities
- **$37,316.00 in risk-weighted monthly-charge exposure**, calculated as probability × monthly charge

Model-weighted expected churners and risk-weighted exposure are expectations under the current model and calibration. They are not counts of customers known to churn or realized financial losses.

In [62]:
from src.retention_strategy import (
    INTERVENTION_CATALOG,
    SCENARIOS,
    run_retention_strategy,
    simulate_campaign,
)

retention_result = run_retention_strategy(
    feature_path=FEATURE_DATA_PATH,
    score_path=Path("artifacts/evaluation/portfolio_risk_scores.csv"),
)
campaign_population = retention_result["campaign"]
retention_scenarios = retention_result["scenario_results"]
base_intervention_results = retention_result["base_by_intervention"]
retention_sensitivity = retention_result["sensitivity"]
intervention_catalog = retention_result["intervention_catalog"]

print(f"Eligible active customers: {len(campaign_population):,}")
print(f"Model-weighted expected churners: {retention_result['report']['model_weighted_expected_churners']:.2f}")

Eligible active customers: 947
Model-weighted expected churners: 502.25


## 13.2 Avoiding Segment Double Counting

Customers frequently belong to several risk segments. To create an operational campaign list, each eligible customer receives one primary intervention through this hierarchy:

1. High-value/high-risk outreach
2. Early-tenure fiber assurance
3. Early-tenure onboarding
4. Senior/high-charge assistance
5. Fiber quality and contract response
6. Premium-support bundle and contract response
7. San Diego investigation
8. Competitor-response/general retention fallback

All overlapping flags remain in the campaign file for secondary analysis, but financial totals use only the mutually exclusive primary assignment. Only four customers have San Diego investigation as their primary action because most high-risk San Diego customers qualify for an earlier, more specific intervention; this does not remove them from geographic investigation.

## 13.3 Recommended Intervention Portfolio

| Primary intervention | Customers | Recommended action |
|---|---:|---|
| High-value outreach | 319 | Dedicated specialist and personalized value-protection review |
| Fiber quality and contract | 165 | Diagnose fiber experience before offering longer commitment |
| Early onboarding | 137 | Structured 30/60/90-day onboarding and service education |
| Early fiber assurance | 127 | Early service-health check, rapid resolution, and plan review |
| Support bundle and contract | 105 | Time-limited premium support plus contract-value option |
| Competitor-response retention | 65 | Personalized device, data, speed, or value response |
| Senior assistance | 25 | Accessible bill review, assisted support, and service-fit consultation |
| San Diego investigation | 4 primary | Local operational and competitor root-cause investigation |

Interventions are designed as testable hypotheses. They should be reviewed for operational feasibility, customer consent, fairness, and cost before launch.

In [63]:
intervention_counts = (
    campaign_population.groupby("primary_intervention", observed=True)
    .agg(
        customers=("customer_id", "size"),
        average_probability=("predicted_churn_probability", "mean"),
        monthly_charge_exposure=("monthly_charge", "sum"),
        cltv=("cltv", "sum"),
    )
    .reset_index()
    .sort_values("customers", ascending=True)
)
fig = px.bar(
    intervention_counts, x="customers", y="primary_intervention", orientation="h",
    color="average_probability", color_continuous_scale="OrRd",
    text="customers", hover_data=["monthly_charge_exposure", "cltv"],
    title="High-Risk Active Customers by Primary Retention Intervention",
)
fig.update_xaxes(title="Eligible customers")
fig.update_yaxes(title=None)
fig.update_layout(template="plotly_white", height=540, coloraxis_colorbar_title="Average<br>risk")
fig.show()

## 13.4 Simulation Formulas

For each scenario:

- **Expected reached customers** = eligible customers × reach rate
- **Expected offer acceptors** = eligible × reach rate × acceptance rate
- **Expected customers saved** = sum of churn probabilities × reach × acceptance × incremental save rate
- **Contact cost** = eligible customers × contact cost per target
- **Offer cost** = sum of intervention costs × reach × acceptance × cost multiplier
- **Expected retained gross margin** = sum(probability × monthly charge) × reach × acceptance × save rate × retained months × gross-margin rate
- **Estimated net benefit** = retained gross margin − contact cost − offer cost
- **Estimated ROI** = net benefit ÷ total campaign cost

The incremental save rate must represent additional retention caused by treatment, not the raw percentage of contacted customers who remain. It can only be measured credibly through a treatment/control design.

## 13.5 Scenario Assumptions

| Assumption | Conservative | Base | Optimistic |
|---|---:|---:|---:|
| Reach rate | 60% | 75% | 85% |
| Offer acceptance | 35% | 50% | 65% |
| Incremental save rate among expected churners reached and accepting | 25% | 35% | 50% |
| Retention horizon | 6 months | 12 months | 18 months |
| Gross-margin rate | 70% | 70% | 70% |
| Contact cost per eligible customer | $4 | $4 | $4 |
| Intervention-cost multiplier | 1.20× | 1.00× | 0.90× |

These are illustrative portfolio assumptions, not observed company results. They are intentionally exposed for sensitivity analysis and future dashboard editing.

## 13.6 Scenario Results

| Result | Conservative | Base | Optimistic |
|---|---:|---:|---:|
| Expected customers saved | 26.37 | 65.92 | 138.75 |
| Campaign cost | $16,272.08 | $22,365.50 | $28,421.77 |
| Expected retained gross margin | $8,228.18 | $41,140.89 | $129,887.65 |
| Estimated net benefit | **−$8,043.90** | **$18,775.39** | **$101,465.89** |
| Estimated ROI | −49.43% | 83.95% | 357.00% |
| Cost per expected save | $617.12 | $339.28 | $204.85 |

The conservative scenario loses money because a short six-month horizon and low incremental save rate do not recover contact and offer costs. The base and optimistic scenarios are positive, but their results depend directly on unverified campaign assumptions. The range—not the best case—is the decision-relevant finding.

In [64]:
display(retention_scenarios.round(2))
scenario_plot = retention_scenarios.melt(
    id_vars="scenario",
    value_vars=["total_campaign_cost", "expected_retained_gross_margin", "estimated_net_benefit"],
    var_name="measure", value_name="amount",
)
fig = px.bar(
    scenario_plot, x="scenario", y="amount", color="measure", barmode="group",
    color_discrete_map={
        "total_campaign_cost": ORANGE,
        "expected_retained_gross_margin": TEAL,
        "estimated_net_benefit": BLUE,
    },
    title="Retention Scenario Economics",
)
fig.add_hline(y=0, line_color="#4D5966", line_width=1)
fig.update_yaxes(title="Estimated amount ($)", tickprefix="$", separatethousands=True)
fig.update_xaxes(title=None)
fig.update_layout(template="plotly_white", legend_title=None)
fig.show()

,scenario,eligible_customers,model_weighted_expected_churners,expected_reached_customers,expected_offer_acceptors,expected_customers_saved,contact_cost,expected_offer_cost,total_campaign_cost,expected_retained_gross_margin,estimated_net_benefit,estimated_roi,cost_per_expected_save,reach_rate,acceptance_rate,incremental_save_rate,retention_horizon_months,gross_margin_rate,contact_cost_per_target,offer_cost_multiplier
0,Conservative,947,502.25,568.20,198.87,26.37,3788.0,12484.08,16272.08,8228.18,-8043.90,-0.49,617.12,0.60,0.35,0.25,6,0.7,4.0,1.2
1,Base,947,502.25,710.25,355.12,65.92,3788.0,18577.50,22365.50,41140.89,18775.39,0.84,339.28,0.75,0.50,0.35,12,0.7,4.0,1.0
2,Optimistic,947,502.25,804.95,523.22,138.75,3788.0,24633.76,28421.76,129887.65,101465.89,3.57,204.85,0.85,0.65,0.50,18,0.7,4.0,0.9


## 13.7 Base Scenario by Intervention

Under base assumptions, every primary intervention has positive estimated net benefit, but scale and ROI differ:

- Fiber quality and contract: **$5,262** estimated net benefit
- Early fiber assurance: **$5,012**
- High-value outreach: **$4,630**
- Early onboarding: **$1,477**
- Senior assistance: **$1,147**
- Competitor-response retention: **$638**
- Support bundle and contract: **$481**
- San Diego investigation: **$128** on the four primary-assignment customers

High ROI in a very small segment should not outrank a larger intervention automatically. Decisions should balance net benefit, customer reach, operational feasibility, uncertainty, fairness, and learning value.

In [65]:
fig = px.bar(
    base_intervention_results.sort_values("estimated_net_benefit"),
    x="estimated_net_benefit", y="primary_intervention", orientation="h",
    color="estimated_roi", color_continuous_scale="Tealgrn",
    hover_data=["eligible_customers", "expected_customers_saved", "total_campaign_cost"],
    title="Base-Scenario Estimated Net Benefit by Primary Intervention",
)
fig.update_xaxes(title="Estimated net benefit ($)", tickprefix="$")
fig.update_yaxes(title=None)
fig.update_layout(template="plotly_white", height=540, coloraxis_colorbar_title="ROI")
fig.show()

## 13.8 Sensitivity and Break-Even Insight

With other base assumptions fixed, a 15% incremental save rate produces negative net benefit across acceptance rates from 30% to 70%. At a 25% save rate, the campaign becomes positive across the tested acceptance range.

Higher acceptance can reduce net benefit when the save rate is too low because more customers receive an offer without enough incremental retention value. This demonstrates why offer acceptance alone is not a sufficient campaign success metric. Incremental saves and retained margin must be measured.

In [66]:
sensitivity_matrix = retention_sensitivity.pivot(
    index="incremental_save_rate", columns="acceptance_rate", values="estimated_net_benefit"
)
fig = px.imshow(
    sensitivity_matrix, text_auto="$,.0f", aspect="auto",
    color_continuous_scale=[RED, "#F2F4F7", TEAL], color_continuous_midpoint=0,
    title="Estimated Net Benefit Sensitivity — Base Assumptions Otherwise Fixed",
)
fig.update_xaxes(title="Offer acceptance rate", tickformat=".0%")
fig.update_yaxes(title="Incremental save rate", tickformat=".0%")
fig.update_layout(template="plotly_white", coloraxis_colorbar_title="Net benefit")
fig.show()

## 13.9 Recommended Pilot Design

1. Select one or two operationally feasible segments, such as early fiber assurance and month-to-month support bundles.
2. Randomly assign eligible customers within each segment to treatment and business-as-usual control groups.
3. Predefine reach, acceptance, incremental retention, cost, gross-margin, and customer-experience metrics.
4. Measure retention at 30, 90, 180, and 365 days where possible.
5. Estimate incremental lift as treatment retention minus control retention, not raw treatment retention.
6. Monitor complaint rates, plan downgrades, fairness, and unintended customer harm.
7. Update scenario assumptions with observed results before scaling.
8. Preserve a control population so model targeting and treatment impact can be evaluated separately.

The model determines whom to consider contacting; the experiment determines whether the intervention works.

## 13.10 Decision Guidance

- Do not launch the optimistic scenario as a forecast; use it as an upper sensitivity case.
- Treat the base scenario as a planning hypothesis requiring pilot validation.
- Use the conservative scenario to understand downside exposure and stop-loss conditions.
- Prioritize actions that solve service or support problems before relying on discounts.
- Protect high-value customers without denying benefits to lower-value customers unfairly.
- Do not contact customers solely because of age or another protected characteristic.
- Report campaign results net of contact and offer costs.
- Maintain intervention-level treatment/control results for continuous learning.

In [67]:
stage_13_checks = pd.Series({
    "Campaign contains 947 eligible active customers": len(campaign_population) == 947,
    "Primary interventions are mutually exclusive": campaign_population["customer_id"].nunique() == len(campaign_population),
    "Eight intervention types assigned": campaign_population["primary_intervention"].nunique() == 8,
    "Three scenarios produced": set(retention_scenarios["scenario"]) == {"Conservative", "Base", "Optimistic"},
    "Base net benefit reconciles": np.isclose(retention_scenarios.set_index("scenario").loc["Base", "estimated_net_benefit"], 18_775.38567687413),
    "Sensitivity matrix contains 25 cases": len(retention_sensitivity) == 25,
    "All retention artifacts exported": all(path.exists() for path in retention_result["paths"].values()),
})
display(stage_13_checks.to_frame("Passed"))
assert stage_13_checks.all(), "At least one Stage 13 validation failed."

,Passed
Campaign contains 947 eligible active customers,True
Primary interventions are mutually exclusive,True
Eight intervention types assigned,True
Three scenarios produced,True
Base net benefit reconciles,True
Sensitivity matrix contains 25 cases,True
All retention artifacts exported,True


## Stage 13 Deliverable — Actionable Retention Strategy and Scenario Analysis

The project now has a mutually exclusive intervention assignment for 947 high-risk active customers, a documented action catalogue, editable conservative/base/optimistic assumptions, segment-level economics, and a 25-case sensitivity matrix. The base scenario estimates 65.92 customers saved and $18,775.39 net benefit, while the conservative scenario is negative—demonstrating that retention value depends on incremental effectiveness, time horizon, and cost. All results remain planning scenarios until validated through controlled campaigns.

---

**Developed and Designed by Emmanuel Onuoha**